// 종목 추천 데이터 — 배치(batch) 단위로 기록되며, 새 추천이 생성될 때마다 batches 맨 앞에 추가됩니다.
// 과거 배치는 수정하지 않습니다(히스토리 보존).
window.RECO = {
  // ── 확실성 최우선 자산 (배치 히스토리와 별도의 상시 추천) ──
  sureUpdatedAt: '2026-07-08',
  sureStats: [
    // S&P 500 롤링 기간별 역사적 플러스 확률 (1928~, 출처: macrotrends/rationalwalk/lazyportfolio 종합)
    { period: '1년', winRate: '약 75~80%', worst: '-43% (대공황)', note: '짧게는 진짜 아무도 몰라요' },
    { period: '3년', winRate: '약 81%', worst: '연 -27%', note: '금융위기도 포함된 수치예요' },
    { period: '10년', winRate: '약 94~96%', worst: '연 -1.5% (1999년 시작)', note: '10년 버티면 거의 다 이겼어요' },
    { period: '15년', winRate: '~100%', worst: '연 +0.6%', note: '역사상 마이너스가 거의 없어요' },
    { period: '20년', winRate: '100%', worst: '연 +3.1%', note: '역사상 단 한 번도 잃지 않았어요' },
    { period: '30년', winRate: '100%', worst: '연 +3.6%', note: '대공황 바닥에 끝나도 플러스!' },
  ],
  sureItems: [
    {
      id: 'sure-sgov', tier: 1, ticker: 'SGOV', name: '아이셰어즈 초단기 미국국채 ETF', market: 'US', exchange: 'NYSE Arca', currency: 'USD',
      horizon: 'long', risk: 'low',
      refPrice: 100.55, refPriceAsOf: '근사치 — 주문 전 현재가 확인 필수',
      buy:  { window: '아무 때나 (미국 장중)', windowKst: '언제 사도 거의 같은 값', low: 100.3, high: 100.8, note: '이 ETF는 매달 초 배당을 주고 가격이 100달러 부근으로 돌아와요. 타이밍 고민이 거의 필요 없어요.' },
      sell: { window: '돈이 필요할 때 아무 때나', windowKst: '언제든 — 급락 위험이 사실상 없음', low: 100.3, high: 104.5, stop: 99.5, note: '만기 3개월 이하 미국 국채 묶음이라 가격이 거의 안 움직여요. 팔고 싶을 때 팔면 돼요.' },
      expectedReturn: { base: 3.6, bull: 4.2, bear: 2.7 },
      scenarios: [
        { name: '낙관', prob: 25, price: 104.7, ret: 4.2, desc: '미국 금리가 지금보다 높게 유지' },
        { name: '기본', prob: 55, price: 104.2, ret: 3.6, desc: '현재 수익률(연 3.5~3.8%) 유지' },
        { name: '비관', prob: 20, price: 103.3, ret: 2.7, desc: '연준 금리 인하 가속 — 그래도 플러스' },
      ],
      rationale: {
        summary: '미국 정부가 3개월 안에 갚는 초단기 국채만 담은 ETF. "미국 정부가 부도나지 않는 한" 원금 손실이 사실상 불가능한, 세상에서 가장 확실한 축에 드는 자산이에요. 현재 연 3.5~3.8% 수준.',
        news: ['2026-07 기준 배당수익률 연 3.5~3.8% (매월 지급)', '7/1 배당락 통과 — 매달 초 배당 지급 사이클', '연준 금리 경로에 따라 수익률이 천천히 변동'],
        technical: ['가격이 $100.0~100.7 사이에서 톱니 모양으로 움직여요 (배당 주고 리셋)', '주가 하락 위험이 사실상 없는 구조'],
        fundamental: ['기초자산: 미국 재무부 단기 국채 (신용등급 세계 최상위)', '운용보수 연 0.09% — 매우 저렴'],
      },
      riskFactors: ['환율: 원화가 강해지면 원화 기준으로는 손해볼 수 있어요 (달러 기준으론 확실)', '미국 금리가 내리면 수익률이 천천히 낮아져요', '미국 정부 부도(역사상 없었음)'],
      dividend: { perShare: 0.30, currency: 'USD', frequency: '매월', schedule: '매월 초 지급 (금리에 따라 변동, 최근 월 $0.29~0.31)', yieldPct: 3.6, next: '2026-08-01 전후', note: '이 ETF는 배당이 곧 수익의 전부예요' },
      simId: 'sure-sgov',
    },
    {
      id: 'sure-kofr', tier: 1, ticker: '423160.KS', name: 'KODEX KOFR금리액티브 ETF', market: 'KR', exchange: 'KRX', currency: 'KRW',
      horizon: 'long', risk: 'low',
      refPrice: 112000, refPriceAsOf: '근사치 — 주문 전 현재가 확인 필수',
      buy:  { window: '아무 때나 (한국 장중 09:00–15:30)', windowKst: '언제 사도 거의 같은 값', low: 111500, high: 112500, note: '하루하루 아주 조금씩(무위험 금리만큼) 오르는 구조라 타이밍이 필요 없어요.' },
      sell: { window: '돈이 필요할 때 아무 때나', windowKst: '언제든 — 사실상 파킹통장', low: 112000, high: 114800, stop: 111000, note: '단 하루를 맡겨도 그만큼 이자가 붙어요. 증권사 파킹통장처럼 쓰면 돼요.' },
      expectedReturn: { base: 2.5, bull: 2.9, bear: 2.1 },
      scenarios: [
        { name: '낙관', prob: 25, price: 114900, ret: 2.9, desc: '한국 기준금리 동결 장기화' },
        { name: '기본', prob: 55, price: 114800, ret: 2.5, desc: '기준금리 2.50% 부근 유지' },
        { name: '비관', prob: 20, price: 114400, ret: 2.1, desc: '금리 인하 — 그래도 플러스' },
      ],
      rationale: {
        summary: '한국 무위험 지표금리(KOFR)를 매일 쌓아 주는 ETF. 출시 이후 단 하루도 가격이 떨어진 적이 없는 구조예요. 한국은행 기준금리 2.50% 시대의 "확실한 이익" — 대신 수익률은 연 2%대로 낮아요.',
        news: ['한국은행 기준금리 2.50% 유지 (여덟 번째 연속 동결)', '다음 금통위 7/16 — 인하 시 수익률 소폭 하락', '2026 국내경제 2.6% 성장 전망 속 완화 사이클'],
        technical: ['상장 이후 일간 수익률이 음수였던 날이 사실상 없음', '그래프가 계단처럼 우상향하는 유일한 유형의 자산'],
        fundamental: ['기초: 국채·통안채 담보 하루짜리 환매조건부채권(RP) 금리', '원화 자산이라 환율 걱정 없음'],
      },
      riskFactors: ['기준금리가 내려가면 수익률도 같이 내려가요', '물가상승률(3.2%)보다 낮으면 실질 구매력은 줄 수 있어요', '증권사 예탁 관련 극단적 시스템 리스크(사실상 이론적)'],
      dividend: null,
      simId: 'sure-kofr',
    },
    {
      id: 'sure-voo', tier: 2, ticker: 'VOO', name: '뱅가드 S&P 500 ETF (장기 적립)', market: 'US', exchange: 'NYSE Arca', currency: 'USD',
      horizon: 'long', risk: 'mid',
      refPrice: 692, refPriceAsOf: '근사치 (S&P 500 7,537 기준 환산) — 주문 전 확인',
      buy:  { window: '매달 같은 날 정액 적립 (미국 장중)', windowKst: '예: 매달 25일 월급날마다 — 타이밍 고민 금지가 핵심', low: 620, high: 700, note: '한 번에 몰빵하지 말고 매달 같은 금액씩. 떨어진 달엔 같은 돈으로 더 많이 사져요(적립식의 마법).' },
      sell: { window: '10년 이상 뒤, 돈이 필요해질 때', windowKst: '2036년 이후 분할 매도 권장', low: 900, high: 1400, stop: 585, note: '역사상 15년 이상 보유 시 손실 확률 ~0%. 중간에 -30% 폭락이 와도 파는 게 아니라 더 사는 자산이에요.' },
      expectedReturn: { base: 7.0, bull: 12.0, bear: -15.0 },
      scenarios: [
        { name: '낙관', prob: 30, price: 775, ret: 12.0, desc: '1년 기준 — AI 붐 지속' },
        { name: '기본', prob: 45, price: 740, ret: 7.0, desc: '1년 기준 — 역사 평균 수준' },
        { name: '비관', prob: 25, price: 588, ret: -15.0, desc: '1년 기준 — 조정. 장기 적립엔 오히려 기회' },
      ],
      rationale: {
        summary: '미국 대표 500개 기업을 통째로 사는 ETF. 1년은 4번 중 1번꼴로 잃지만, 역사상 20년 이상 보유하면 단 한 번도 잃지 않았어요(최악의 20년도 연 +3.1%). "시간"을 재료로 확실함을 만드는 전략이에요.',
        news: ['S&P 500 7,537 (7/6) — 사상 최고 부근, 과열 경고도 병존', '증권가 연말 목표 7,100(-5%) 전망도 있음 — 그래서 적립식', '배당수익률 약 1.1~1.3%, 분기 지급'],
        technical: ['역사적 롤링 승률: 1년 ~80% / 10년 ~95% / 20년 100%', '최악의 10년(1999 시작)도 연 -1.5%에 그침'],
        fundamental: ['미국 경제 전체에 분산 — 개별 회사 파산 위험이 사라져요', '운용보수 연 0.03% — 사실상 공짜'],
      },
      riskFactors: ['1~3년 단기엔 -20~40% 하락 가능 (버틸 수 있는 돈으로만)', '환율 변동 (원화 기준 수익률)', '"이번엔 다르다"는 역사상 늘 틀렸지만, 미래가 과거와 같다는 보장 역시 없음'],
      dividend: { perShare: 1.80, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급 (최근 분기 $1.7~1.9)', yieldPct: 1.1, next: '2026-09월 예상', note: '배당은 재투자(자동 적립)가 정석이에요' },
      simId: 'sure-voo',
    },
    {
      id: 'sure-k200', tier: 2, ticker: '069500.KS', name: 'KODEX 200 (한국 대표기업 200)', market: 'KR', exchange: 'KRX', currency: 'KRW',
      horizon: 'long', risk: 'mid',
      refPrice: 103300, refPriceAsOf: '근사치 (코스피 7,656 기준 환산) — 주문 전 확인',
      buy:  { window: '매달 같은 날 정액 적립 (한국 장중)', windowKst: '예: 매달 급여일 — 7/7 서킷브레이커급 급락 후 적립 시작엔 나쁘지 않은 자리', low: 95000, high: 105000, note: '어제(7/7) 코스피가 -4.9%(장중 -8%, 서킷브레이커) 급락했어요. 적립식은 이런 날 시작해도 무섭지 않아요 — 매달 나눠 사니까요.' },
      sell: { window: '10년 이상 뒤 분할 매도', windowKst: '2036년 이후', low: 130000, high: 180000, stop: 87000, note: '한국 시장은 미국보다 출렁임이 커요. 그래서 더더욱 장기+적립이 답이에요.' },
      expectedReturn: { base: 6.5, bull: 13.0, bear: -18.0 },
      scenarios: [
        { name: '낙관', prob: 30, price: 113600, ret: 10.0, desc: '1년 기준 — 반도체 슈퍼사이클 지속' },
        { name: '기본', prob: 45, price: 110000, ret: 6.5, desc: '1년 기준 — 완만한 회복' },
        { name: '비관', prob: 25, price: 84700, ret: -18.0, desc: '1년 기준 — 사이클 꺾임. 적립엔 기회' },
      ],
      rationale: {
        summary: '삼성전자·SK하이닉스 등 한국 대표 200개 기업을 한 번에 사는 ETF. 2026년 코스피는 8,300까지 올랐다가 7/7 서킷브레이커급 급락(-4.9%)을 겪는 롤러코스터 중 — 개별 종목 대신 시장 전체를 적립식으로 사는 것이 초보에게 훨씬 확실한 접근이에요.',
        news: ['코스피 7,656 (7/7, -4.91% 급락·장중 서킷브레이커 발동)', '7/1에도 -2.04% (8,303) — 고점 대비 조정 국면', '반도체 수출 호조로 2026년 한국 경제 2.6% 성장 전망'],
        technical: ['고점(8,300선) 대비 약 -8% 조정 구간', '급등 후 조정 국면 — 적립식 분할 진입에 유리한 변동성'],
        fundamental: ['반도체·배터리·바이오 등 한국 핵심 산업 분산', '배당 + 밸류업 정책 수혜'],
      },
      riskFactors: ['한국 시장 변동성은 미국보다 커요 (연 20%대)', '반도체 사이클 의존도가 높아요', '지정학(북한·미중) 리스크', '단기 -30% 이상 하락 가능 — 장기 적립 전제 필수'],
      dividend: { perShare: 1300, currency: 'KRW', frequency: '분기', schedule: '1·4·7·10월 말 분배금 (연 1,300원 안팎, 변동)', yieldPct: 1.3, next: '2026-07월 말', note: '분배금은 재투자가 정석이에요' },
      simId: 'sure-k200',
    },
  ],
  meta: {
    fxUsdKrw: 1528.7, // 2026-07-06 기준 참고 환율
    taxNote: '한국 거주 개인투자자 기준. 미국주식 양도차익: 연 250만원 공제 후 22%(지방소득세 포함), 미국 배당: 15% 원천징수. 국내 상장주식(소액주주 장내): 양도세 없음, 매도 시 증권거래세 0.15%, 국내 배당: 15.4% 원천징수. 금융소득 연 2,000만원 초과 시 종합과세 대상.',
    disclaimer: '본 서비스는 정보 제공 목적의 시뮬레이션 도구이며 투자 자문이 아닙니다. 모든 수치는 몬테카를로 시뮬레이션(경로 20,000개, GBM 모형)에 기반한 확률 추정치로, 실제 수익을 보장하지 않습니다. 원금 손실이 발생할 수 있으며 투자 판단과 책임은 투자자 본인에게 있습니다.',
  },
  batches: [
    {
      id: 'batch-2026-07-09',
      generatedAt: '2026-07-09T08:10+09:00 (매일 아침 자동 갱신)',
      pricesAsOf: '기준가 2026-07-08 종가 (일부 근사치 — 주문 전 확인)',
      title: '2026-07-09 아침 자동 갱신 (미 반도체 반등 · 한국 반등 시도)',
      marketSnapshot:
        '밤사이 미 증시: 다우 -1%(중동 리스크), S&P -0.2%, 나스닥 +0.2% — 반도체는 반등(브로드컴 +4~5% 애플 커스텀칩 계약 2031년까지 연장, AMD +6.6%, 엔비디아 +0.7% $196.93). 연준 6월 의사록: 일부 위원 "인플레 지속 시 추가 인상 가능" 매파 발언. 트럼프 "이란 타격 계속될 수 있다" — WTI $74대 유지. 한국 7/8: 코스피 -5.35% 7,246.79, 삼성전자 -6.25%(약 277,500원), SK하이닉스 -5.68%(약 2,076,000원). 오늘(7/9) 미 반도체 반등을 따라 한국 반등 시도 예상 — 단 중동 헤드라인이 상시 변수.',
      picks: [
        // ─────────────── 당일 (7/9) ───────────────
        {
          id: 'b3-day-samsung', ticker: '005930.KS', name: '삼성전자 (4일 만의 반등 시도)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'day', risk: 'high',
          refPrice: 277500, refPriceAsOf: '2026-07-08 종가(약, -6.25% 반영) — 주문 전 확인',
          buy:  { window: '2026-07-09 09:00–09:40 (한국 KST)', windowKst: '오늘 오전 9:00–9:40', low: 270000, high: 277000, note: '밤사이 미 반도체 반등(AMD +6.6%, 엔비디아 +0.7%)이 반등 재료. 갭상승 +2% 이상 출발이면 추격하지 말고 눌림 대기.' },
          sell: { window: '2026-07-09 14:30–15:20 (한국 KST)', windowKst: '오늘 오후 2:30–3:20', low: 283000, high: 288000, stop: 265000, note: '당일 전량 정리. 265,000원 이탈 시 즉시 손절 — 3일 -12% 급락 뒤라 변동성 극대.' },
          expectedReturn: { base: 2.2, bull: 3.8, bear: -4.5 },
          scenarios: [
            { name: '낙관', prob: 28, price: 288000, ret: 3.8, desc: '미 반도체 훈풍 + 낙폭과대 매수세' },
            { name: '기본', prob: 44, price: 283500, ret: 2.2, desc: '기술적 반등 — 낙폭 일부 회복' },
            { name: '비관', prob: 28, price: 265000, ret: -4.5, desc: '중동 헤드라인 악화 — 손절' },
          ],
          rationale: {
            summary: '3일 연속 급락(-12%) 직후 + 밤사이 미국 반도체 반등(나스닥 +0.2%, AMD +6.6%)이라는 반등 재료가 갖춰진 날. 4거래일 만의 되돌림을 노리되, 이란 타격 지속 가능성이 있어 손절 규율이 필수.',
            news: ['밤사이 미 반도체 반등 — 브로드컴 애플 계약 연장(+4~5%), AMD +6.6%', '7/8 삼성전자 -6.25% — 3일 누적 약 -12% 과매도 극단', '트럼프 "이란 타격 계속될 수 있다" — 리스크 상존'],
            technical: ['270,000 심리적 지지 / 285,000–290,000 저항', 'RSI 2년 내 최저권 — 반등 탄력 구간', '거래량 폭증 후 첫 반등 시도일'],
            fundamental: ['HBM4·파운드리 스토리 불변 — 급락은 매크로 요인', '증권가 목표가 대비 -45% 지점'],
          },
          riskFactors: ['장중 중동 속보(최대 변수)', '외국인 순매도 4일차 연장 여부', '유가 $76 돌파 시 재차 리스크오프', '갭상승 출발 시 되밀림 위험'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원', yieldPct: 0.52, next: '2026-08월 지급 예정', note: '당일 전략에선 배당 무관' },
          simId: 'b3-day-samsung',
        },
        {
          id: 'b3-day-hynix', ticker: '000660.KS', name: 'SK하이닉스 (미 칩 랠리 수혜)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'day', risk: 'veryhigh',
          refPrice: 2076000, refPriceAsOf: '2026-07-08 종가(약, -5.68% 반영) — 주문 전 확인',
          buy:  { window: '2026-07-09 09:00–10:00 (한국 KST)', windowKst: '오늘 오전 9:00–10:00', low: 2020000, high: 2080000, note: '미국 AI 칩 반등(AMD·브로드컴)과 상관관계가 가장 높은 국내 종목. 고점 대비 -30% 폭락 후 첫 반등 시도.' },
          sell: { window: '2026-07-09 14:30–15:20 (한국 KST)', windowKst: '오늘 오후 2:30–3:20', low: 2150000, high: 2200000, stop: 1960000, note: '당일 전량 정리. 하루 ±9% 움직이는 구간 — 목표 도달 즉시 기계적 청산.' },
          expectedReturn: { base: 3.8, bull: 6.0, bear: -5.6 },
          scenarios: [
            { name: '낙관', prob: 27, price: 2200000, ret: 6.0, desc: '미 칩 랠리 추종 강반등' },
            { name: '기본', prob: 43, price: 2155000, ret: 3.8, desc: '낙폭 일부 되돌림' },
            { name: '비관', prob: 30, price: 1960000, ret: -5.6, desc: '리스크오프 재점화 — 손절' },
          ],
          rationale: {
            summary: '2주간 -30% 폭락(역대 최대 일일 폭락 포함) 후, 밤사이 미국 AI 칩주 반등이 직접적 반등 재료. 나스닥 상장 계획 재료도 살아 있음 — 극단적 변동성 구간의 하루 반등 트레이드로, 이번 배치에서 가장 위험하고 가장 보상 큰 당일 전략.',
            news: ['밤사이 AMD +6.6%, 브로드컴 +4~5% — AI 칩 반등', '7/2 역대 최대 폭락(하루 시총 534조 증발 사태) 이후 극단 변동성', '나스닥 상장 계획 — 중기 재료 유효'],
            technical: ['2,000,000 심리 지지 / 2,200,000 저항', '고점 2,987,000 대비 -30% — 낙폭 극단', '변동성 연 60% — 포지션 최소화 필수'],
            fundamental: ['HBM 공급 주도권 — AI 수요 구조 불변', 'D램 가격 사이클 지속 여부가 중기 관건'],
          },
          riskFactors: ['하루 ±9% 변동 — 손절 미준수 시 대형 손실', '중동 속보 리스크', 'AI 고점론 재점화 가능성', '외국인 수급'],
          dividend: { perShare: 1200, currency: 'KRW', frequency: '분기', schedule: '분기 고정 300원 + 실적연동', yieldPct: 0.06, next: '2026-08월 지급 예정', note: '당일 전략에선 무관' },
          simId: 'b3-day-hynix',
        },
        {
          id: 'b3-day-nvda', ticker: 'NVDA', name: '엔비디아 (반등 연장)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'day', risk: 'high',
          refPrice: 196.93, refPriceAsOf: '2026-07-08 종가(달러, +0.7%)',
          buy:  { window: '2026-07-09 09:30–10:30 (미국 ET)', windowKst: '오늘 밤 22:30–23:30', low: 193, high: 197, note: '어제 시장 하락 속 +0.7% 상대 강세 — BofA 매수 의견 + 브로드컴發 AI 칩 훈풍 연장 노림.' },
          sell: { window: '2026-07-09 14:00–15:45 (미국 ET)', windowKst: '내일 새벽 03:00–04:45', low: 200, high: 203, stop: 190, note: '당일 청산. $190 이탈 시 즉시 손절.' },
          expectedReturn: { base: 1.9, bull: 3.4, bear: -3.5 },
          scenarios: [
            { name: '낙관', prob: 28, price: 203, ret: 3.4, desc: 'AI 칩 랠리 2일차 연장' },
            { name: '기본', prob: 44, price: 200.5, ret: 1.9, desc: '$200 회복 시도' },
            { name: '비관', prob: 28, price: 190, ret: -3.5, desc: '중동·금리 리스크오프 — 손절' },
          ],
          rationale: {
            summary: '다우 -1% 하락일에 +0.7% 오른 상대 강세 — 브로드컴·AMD發 AI 칩 반등의 중심 수혜. BofA "7년 최저 밸류에이션" 매수 의견과 함께 $200 회복 시도를 노리는 당일 전략.',
            news: ['7/8 +0.71% $196.93 — 하락장 속 상대 강세', '브로드컴-애플 계약 연장으로 AI 하드웨어 심리 개선', 'BofA 매수 유지 — "강화된 매수 기회"'],
            technical: ['$193–195 지지 / $200(심리)–203 저항', '5월 고점 대비 -16% — 회복 여지', '반도체 지수 반등 2일차 여부가 관건'],
            fundamental: ['선행 PER 18배 — 밸류에이션 하단', 'AI 인프라 수요 구조 불변'],
          },
          riskFactors: ['연준 의사록 매파 잔향 — 금리 우려', '중동 속보', 'AI 고점론 헤드라인', '$200 매물벽'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당' },
          simId: 'b3-day-nvda',
        },
        // ─────────────── 1주 ───────────────
        {
          id: 'b3-week-tsm', ticker: 'TSM', name: 'TSMC (실적 D-7 런업)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'mid',
          refPrice: 434.16, refPriceAsOf: '2026-07-07 종가(달러) — 7/8 칩 반등으로 상승 가능성',
          buy:  { window: '2026-07-09–07-10 (미국 ET)', windowKst: '오늘 밤–금요일 새벽', low: 428, high: 445, note: '칩 섹터 반등 확인 후 실적(7/16) 런업 진입 — 반등 초입이라 진입가를 소폭 상향.' },
          sell: { window: '2026-07-15 14:00–16:00 (미국 ET)', windowKst: '7/16(목) 새벽 03:00–05:00', low: 455, high: 465, stop: 415, note: '실적 발표 전 차익 실현 원칙 유지.' },
          expectedReturn: { base: 4.3, bull: 6.4, bear: -4.4 },
          scenarios: [
            { name: '낙관', prob: 30, price: 462, ret: 6.4, desc: '칩 반등 + 실적 기대 겹침' },
            { name: '기본', prob: 45, price: 453, ret: 4.3, desc: '완만한 런업' },
            { name: '비관', prob: 25, price: 415, ret: -4.4, desc: '리스크오프 재점화 — 손절' },
          ],
          rationale: {
            summary: '실적 D-7. 브로드컴-애플 계약 연장으로 커스텀 칩 생태계 전체의 파운드리 수요 재확인 — TSMC가 그 생산기지. 어닝 서프라이즈 이력 + 칩 섹터 반등 초입이 겹친 런업 구간.',
            news: ['실적 7/16 발표 — D-7 런업 구간', '브로드컴 애플 칩 2031년까지 연장 — 파운드리 수요 청신호', '칩 섹터 반등 개시 (7/8 미국장)'],
            technical: ['$428–435 지지 / $455–465 저항', '고점 대비 -9% — 회복 여지', '실적 전 주 상승 경향(8분기 중 6회)'],
            fundamental: ['3nm/2nm 독점 — AI·커스텀칩 수요 집중', '추정 EPS $3.80 — 상향 추세'],
          },
          riskFactors: ['대만해협·중동 지정학 이중 리스크', '실적 가이던스 눈높이', '반등 실패 시 되밀림'],
          dividend: { perShare: 0.70, currency: 'USD', frequency: '분기', schedule: '분기 약 $0.70 (ADR)', yieldPct: 0.64, next: '2026-09월 예상', note: 'ADR 수수료·원천세 유의' },
          simId: 'b3-week-tsm',
        },
        {
          id: 'b3-week-xom', ticker: 'XOM', name: '엑슨모빌 (유가 강세 1주)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'mid',
          refPrice: 138.20, refPriceAsOf: '2026-07-07 종가(달러) — 7/8 유가 급등으로 상승했을 가능성',
          buy:  { window: '2026-07-09–07-10 (미국 ET)', windowKst: '오늘 밤–금요일 새벽', low: 137, high: 142, note: '트럼프 "타격 계속" 발언으로 유가 강세가 1주 이상 지속될 수 있는 국면 — 당일에서 1주 보유로 연장.' },
          sell: { window: '2026-07-15–07-16 (미국 ET)', windowKst: '다음 주 수–목', low: 145, high: 148, stop: 134, note: '중동 평화 협상 재개 뉴스가 나오면 목표 미달이어도 즉시 정리.' },
          expectedReturn: { base: 4.0, bull: 6.4, bear: -3.7 },
          scenarios: [
            { name: '낙관', prob: 30, price: 147, ret: 6.4, desc: '유가 $78+ — 에너지 주도장' },
            { name: '기본', prob: 45, price: 144, ret: 4.0, desc: '유가 $74~76 유지' },
            { name: '비관', prob: 25, price: 134, ret: -3.7, desc: '전격 휴전 — 유가 반락, 손절' },
          ],
          rationale: {
            summary: '이란 타격이 "계속될 수 있다"는 국면에서 유가 프리미엄이 1주 이상 유지될 가능성 — 유가 수혜 + 배당 3% + 시장 하락 방어라는 삼중 성격. 하락장 헤지 겸용 1주 포지션.',
            news: ['트럼프 "이란 타격 계속될 수 있다" — 유가 상방 리스크', 'WTI $74대 안착 — 호르무즈 프리미엄', '에너지 섹터 하락장 상대 강세 지속'],
            technical: ['$135–137 지지 / $145–148 저항', '52주 중단 — 상승 여력', '유가 차트 동행 — $70 이탈 시 경계'],
            fundamental: ['배당 연 $4.12(3.0%), 42년 연속 증액', '유가 $70 이상이면 실적 호조 구조'],
          },
          riskFactors: ['전격 휴전 시 유가 급반락(최대)', '전략비축유 방출 등 정책 개입', '수요 둔화 헤드라인'],
          dividend: { perShare: 1.03, currency: 'USD', frequency: '분기', schedule: '분기 $1.03 (연 $4.12)', yieldPct: 3.02, next: '배당락 2026-08월 중순 예상', note: '배당락 전 장기 전환도 고려 가능' },
          simId: 'b3-week-xom',
        },
        {
          id: 'b3-week-ko', ticker: 'KO', name: '코카콜라 (피난처 유지)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'low',
          refPrice: 82.04, refPriceAsOf: '2026-06-30 종가(달러) — 근사치',
          buy:  { window: '2026-07-09 (미국 ET)', windowKst: '오늘 밤', low: 81, high: 84, note: '중동 불확실성 지속 — 피난처 수요 유지. 전 배치와 동일 전략.' },
          sell: { window: '2026-07-16–07-17 (미국 ET)', windowKst: '다음 주 목–금', low: 85, high: 86.5, stop: 79, note: '시장 안정 시 조기 정리 또는 배당 목적 장기 전환.' },
          expectedReturn: { base: 2.4, bull: 4.2, bear: -3.7 },
          scenarios: [
            { name: '낙관', prob: 30, price: 86.5, ret: 4.2, desc: '리스크오프 지속 — 디펜시브 집중' },
            { name: '기본', prob: 50, price: 84, ret: 2.4, desc: '완만한 방어주 선호' },
            { name: '비관', prob: 20, price: 79, ret: -3.7, desc: '위험선호 급반전 — 손절' },
          ],
          rationale: {
            summary: '중동 리스크가 해소되지 않은 상태 — 방어주 로테이션 지속 국면. 하락장에서 오르는 저변동성 종목으로 초보에게 가장 부담 없는 1주 전략 (전 배치에서 유지).',
            news: ['이란 타격 지속 가능성 — 피난처 수요 유지', '연준 의사록 매파 — 금리 민감 성장주 부담', '9월 중순 배당락 접근 중'],
            technical: ['$78–80 강지지 / $85 저항', '하락장 상대강도 상위 유지'],
            fundamental: ['배당 64년 증액 — 위기 검증 완료', '필수소비재 — 전쟁 무관 수요'],
          },
          riskFactors: ['급반전 랠리 시 소외', '금리 상승 시 배당주 매력 하락', '환율'],
          dividend: { perShare: 0.53, currency: 'USD', frequency: '분기', schedule: '분기 $0.53 (연 $2.12)', yieldPct: 2.56, next: '배당락 2026-09-11~15 예상', note: '장기 전환 가치 충분' },
          simId: 'b3-week-ko',
        },
        // ─────────────── 1개월 ───────────────
        {
          id: 'b3-month-msft', ticker: 'MSFT', name: '마이크로소프트 (실적 촉매)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'month', risk: 'mid',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러) — 근사치',
          buy:  { window: '2026-07-09–07-14 분할 (미국 ET)', windowKst: '이번 주 3회 분할', low: 375, high: 390, note: '7월 말 FY26 4분기 실적 전 분할 매수 — 전 배치 전략 유지.' },
          sell: { window: '2026-08-06–08-12 (미국 ET)', windowKst: '8월 초중순', low: 408, high: 420, stop: 362, note: '실적 후 갭 소화 구간 분할 매도.' },
          expectedReturn: { base: 6.5, bull: 8.6, bear: -6.4 },
          scenarios: [
            { name: '낙관', prob: 32, price: 420, ret: 8.6, desc: 'Azure 재가속 확인' },
            { name: '기본', prob: 43, price: 410, ret: 6.0, desc: '완만한 회복' },
            { name: '비관', prob: 25, price: 362, ret: -6.4, desc: 'AI capex 우려 재부각 — 손절' },
          ],
          rationale: {
            summary: '2023년 이후 최저 밸류에이션(선행 21배) + 월가 목표 $560 + 7월 말 실적 촉매 — 3주 안에 실적 이벤트가 오는 1개월 코어 전략 (연속 유지 중).',
            news: ['월가 평균 목표가 $560 (+45%)', '7월 말 FY26 4분기 실적 — Azure 성장률 관건', '연준 매파 의사록 — 단기 밸류에이션 부담 요인'],
            technical: ['$373–378 이중바닥 / $405–410 저항', '나스닥 반등 시 회복 선도 이력'],
            fundamental: ['선행 21배 — 역사적 하단', 'AI capex 회수 사이클 접근'],
          },
          riskFactors: ['실적 가이던스(최대)', '금리 — 의사록 매파 잔향', '중동發 시장 전반 조정'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64)', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '보유 중 배당락 1회 포함 가능' },
          simId: 'b3-month-msft',
        },
        {
          id: 'b3-month-samsung', ticker: '005930.KS', name: '삼성전자 (더 깊어진 낙폭)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'month', risk: 'mid',
          refPrice: 277500, refPriceAsOf: '2026-07-08 종가(약) — 주문 전 확인',
          buy:  { window: '2026-07-09–07-17 분할 (한국 KST)', windowKst: '이번 주~다음 주 4회 분할', low: 262000, high: 280000, note: '어제보다 더 싸진 가격 — 분할 하단을 262,000원까지 낮춤.' },
          sell: { window: '2026-08-10–08-18 (한국 KST)', windowKst: '8월 중순', low: 308000, high: 320000, stop: 255000, note: '7월 말 확정실적이 촉매. 255,000원 이탈 시 정리.' },
          expectedReturn: { base: 9.0, bull: 15.3, bear: -8.1 },
          scenarios: [
            { name: '낙관', prob: 28, price: 320000, ret: 15.3, desc: '중동 안정 + HBM4E 수주 공개' },
            { name: '기본', prob: 45, price: 302500, ret: 9.0, desc: '30만원 회복' },
            { name: '비관', prob: 27, price: 255000, ret: -8.1, desc: '전쟁 확산·사이클 우려 — 손절' },
          ],
          rationale: {
            summary: '고점 대비 -16%, 목표가 대비 -45% — 낙폭이 하루 더 깊어져 기대수익률이 커진 1개월 회복 전략. 펀더멘털 훼손 없는 매크로 급락이라는 판단 유지, 7월 말 확정실적·컨콜이 촉매.',
            news: ['7/8 -6.25% 추가 급락 — 4일간 약 -13%', '밤사이 미 반도체 반등 — 회복 신호 초입', '7월 말 확정실적 — HBM4E 수주 공개 여부 관건'],
            technical: ['262,000–272,000 지지 클러스터', '300,000 회복이 1차 관문', '월봉 추세 유지'],
            fundamental: ['HBM4E 기술 리더십 불변', '목표가 500,000원 대비 극단 괴리'],
          },
          riskFactors: ['중동 전쟁 장기화', '확정실적 부문별 부진', 'D램 가격 흐름', '외국인 수급'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원', yieldPct: 0.52, next: '2026-08월 지급 예정', note: '보유 중 분기배당 1회 포함 예상' },
          simId: 'b3-month-samsung',
        },
        {
          id: 'b3-month-nvda', ticker: 'NVDA', name: '엔비디아 (실적 런업 코어)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'month', risk: 'high',
          refPrice: 196.93, refPriceAsOf: '2026-07-08 종가(달러)',
          buy:  { window: '2026-07-09–07-15 분할 (미국 ET)', windowKst: '이번 주 분할', low: 188, high: 198, note: '반등 초입 — 밀릴 때마다 분할. BofA 매수 논리 유지.' },
          sell: { window: '2026-08-05–08-14 (미국 ET)', windowKst: '8월 초중순 (8월 말 실적 전)', low: 212, high: 220, stop: 178, note: '실적 기대감 정점 구간 분할 매도.' },
          expectedReturn: { base: 7.7, bull: 11.7, bear: -9.6 },
          scenarios: [
            { name: '낙관', prob: 30, price: 220, ret: 11.7, desc: '칩 랠리 재개 + 실적 런업' },
            { name: '기본', prob: 45, price: 212, ret: 7.7, desc: '완만한 회복 후 런업 초입' },
            { name: '비관', prob: 25, price: 178, ret: -9.6, desc: 'AI 고점론 재확산 — 손절' },
          ],
          rationale: {
            summary: '브로드컴發 AI 칩 심리 개선 + BofA "7년 최저 18배" + 8월 말 실적 런업 계절성 — 세 재료가 겹치는 1개월 코어 전략 (연속 유지, 목표 소폭 상향).',
            news: ['AI 칩 반등 개시 — 브로드컴·AMD 급등 (7/8)', 'BofA 매수 유지', '8월 말 FY27 2분기 실적 대기'],
            technical: ['$188–193 지지 / $210–220 저항 밴드', '고점 -16% — 회복 여지'],
            fundamental: ['선행 18배 — 하단 논리', 'CUDA 해자 견고'],
          },
          riskFactors: ['AI 고점론', '중동·금리 매크로', '8월 실적 눈높이', '커스텀칩(브로드컴) 경쟁 서사'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당' },
          simId: 'b3-month-nvda',
        },
        // ─────────────── 장기 (6–12개월) ───────────────
        {
          id: 'b3-long-msft', ticker: 'MSFT', name: '마이크로소프트 (장기 코어)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러) — 근사치',
          buy:  { window: '2026-07-09–09-30 매월 분할 (미국 ET)', windowKst: '7–9월 5회 분할', low: 355, high: 395, note: '변동성 장세 분할 매수 — 전략 유지.' },
          sell: { window: '2027-04월–07월 (미국 ET)', windowKst: '2027년 2분기', low: 480, high: 560, stop: 330, note: '목표 $560 접근 시 단계적 실현.' },
          expectedReturn: { base: 15.1, bull: 34.5, bear: -14.7 },
          scenarios: [
            { name: '낙관', prob: 35, price: 520, ret: 34.5, desc: 'AI capex 수익화 입증' },
            { name: '기본', prob: 45, price: 460, ret: 18.9, desc: '멀티플 정상화' },
            { name: '비관', prob: 20, price: 330, ret: -14.7, desc: '회수 지연 장기화' },
          ],
          rationale: {
            summary: '장기 논리 불변 — 전쟁·유가·단기 금리 어느 것도 12개월 뒤 현금창출력을 바꾸지 못한다. 3년 최저 밸류에이션에서의 분할 매수 지속.',
            news: ['월가 목표 $560 유지', 'Copilot·Azure AI 확대', '변동성 = 분할 매수 기회'],
            technical: ['$373 이중바닥 — 장기 지지', '월봉 상승 구조 불변'],
            fundamental: ['삼중 해자(클라우드+오피스+AI)', '배당 21년 연속 증액'],
          },
          riskFactors: ['AI 회수 속도', '규제', '환율', '경기 침체'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64)', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '12개월 4회 수령' },
          simId: 'b3-long-msft',
        },
        {
          id: 'b3-long-ko', ticker: 'KO', name: '코카콜라 (배당 코어)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 82.04, refPriceAsOf: '2026-06-30 종가(달러) — 근사치',
          buy:  { window: '2026-07-09–09-10 분할 (미국 ET)', windowKst: '9월 초까지 분할 (배당락 전 완료)', low: 78, high: 84, note: '9월 중순 배당락 전 매집 — 전략 유지.' },
          sell: { window: '2027-07월 이후 검토', windowKst: '원칙적 장기 보유', low: 90, high: 95, stop: 72, note: '배당 수령 주목적.' },
          expectedReturn: { base: 7.4, bull: 15.8, bear: -12.2 },
          scenarios: [
            { name: '낙관', prob: 32, price: 95, ret: 15.8, desc: '디펜시브 프리미엄 지속' },
            { name: '기본', prob: 48, price: 88, ret: 7.3, desc: '완만한 우상향 + 배당' },
            { name: '비관', prob: 20, price: 72, ret: -12.2, desc: '소비 둔화 — 손절 기준' },
          ],
          rationale: {
            summary: '64년 연속 배당 증액 — 전쟁 국면에서 가치가 재확인되는 중. 9월 배당락 전 매집 전략 지속.',
            news: ['리스크오프 수혜 지속', '배당락 9/11–15 예상', '인플레 국면 가격 전가력'],
            technical: ['$78–80 장기 지지', '하락장 상대강도 상위'],
            fundamental: ['배당왕 — 위기 검증', '글로벌 브랜드'],
          },
          riskFactors: ['금리 재상승', '수요 트렌드', '달러 강세', '환율'],
          dividend: { perShare: 0.53, currency: 'USD', frequency: '분기', schedule: '분기 $0.53 (연 $2.12)', yieldPct: 2.56, next: '배당락 2026-09-11~15 예상, 지급 10/1', note: '12개월 4회 수령' },
          simId: 'b3-long-ko',
        },
        {
          id: 'b3-long-samsung', ticker: '005930.KS', name: '삼성전자 (장기 — 세일 연장)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'long', risk: 'mid',
          refPrice: 277500, refPriceAsOf: '2026-07-08 종가(약) — 주문 전 확인',
          buy:  { window: '2026-07-09–10-30 매월 분할 (한국 KST)', windowKst: '7–10월 8회 분할', low: 250000, high: 285000, note: '나흘째 더 싸진 가격 — 8회 분할 유지, 하단 250,000원까지 확대.' },
          sell: { window: '2027-04월–07월 (한국 KST)', windowKst: '2027년 2분기', low: 400000, high: 450000, stop: 225000, note: '목표가 50만원 대비 -45% 시작점.' },
          expectedReturn: { base: 15.0, bull: 51.4, bear: -18.9 },
          scenarios: [
            { name: '낙관', prob: 30, price: 420000, ret: 51.4, desc: 'HBM 회복 + 지정학 안정' },
            { name: '기본', prob: 45, price: 355000, ret: 27.9, desc: '사이클 지속 — 쇼크 전 회복' },
            { name: '비관', prob: 25, price: 225000, ret: -18.9, desc: '피크아웃 확인 — 손절' },
          ],
          rationale: {
            summary: '4일 연속 하락으로 장기 진입가가 더 좋아졌다 — 같은 회사, 같은 기술 리더십, 더 싼 가격. 12개월 분할 매수 전략 유지하며 하단만 확대.',
            news: ['4일 누적 약 -13% — 목표가 괴리 -45%', 'HBM4E 슈퍼사이클 구조 지속', '미 반도체 반등 — 바닥 신호 주목'],
            technical: ['250,000–262,000 장기 지지 밴드', '월봉 추세 유지', '과매도 극단'],
            fundamental: ['복합 포트폴리오 + 분기배당', 'HBM 점유율 회복 = 리레이팅'],
          },
          riskFactors: ['중동 장기화', '사이클 피크아웃', 'HBM 경쟁', '환율'],
          dividend: { perShare: 1444, currency: 'KRW', frequency: '분기', schedule: '분기 361원 × 4회', yieldPct: 0.52, next: '2026-08월 지급 예정', note: '12개월 4회 수령' },
          simId: 'b3-long-samsung',
        },
      ],
    },
    {
      id: 'batch-2026-07-08-2',
      generatedAt: '2026-07-08T23:55+09:00',
      pricesAsOf: '기준가 2026-07-07~08 종가 (미국은 7/8 장중 변동 지속)',
      title: '2026-07-08 밤 갱신 (중동 리스크 재점화 · 코스피 3일 급락)',
      marketSnapshot:
        '미·이란 갈등 재격화 — 호르무즈 해협 상선 3척 피격에 미군이 이란 타격, 트럼프 "합의 종료" 선언. WTI +5.2% $74.16. 미 증시 7/8 장중 하락(다우 -1.2%, S&P -0.6%, 나스닥 -0.5%), FOMC 의사록 발표일. 코스피 3일 연속 급락 7,246.79(-5.4%, 장중 7,000 위협·이번 주 서킷브레이커 2회), 삼성전자 281,500원(-4.9%), AI 고점론 확산. BofA는 엔비디아 "7년 최저 선행 PER 18배 — 강화된 매수 기회" 평가. 이 배치는 사이트 갱신 요청(#3)으로 생성.',
      picks: [
        // ─────────────── 당일 ───────────────
        {
          id: 'b2-day-samsung', ticker: '005930.KS', name: '삼성전자 (낙폭과대 반등)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'day', risk: 'high',
          refPrice: 281500, refPriceAsOf: '2026-07-08 종가(원)',
          buy:  { window: '2026-07-09 09:00–09:40 (한국 KST)', windowKst: '7/9(목) 09:00–09:40', low: 272000, high: 279000, note: '3일 연속 급락(-6.9%→-4.9%) 후 반등 시도 노림. 단, 밤사이 중동 헤드라인 악화 시(유가 $78 돌파 등) 진입 자체를 포기할 것.' },
          sell: { window: '2026-07-09 14:30–15:20 (한국 KST)', windowKst: '7/9(목) 14:30–15:20', low: 286000, high: 291000, stop: 268000, note: '당일 전량 정리. 268,000원 이탈 시 즉시 손절 — 중동 리스크 장세에선 손절 규율이 생명.' },
          expectedReturn: { base: 1.9, bull: 3.4, bear: -4.8 },
          scenarios: [
            { name: '낙관', prob: 25, price: 291000, ret: 3.4, desc: '중동 완화 헤드라인 + 낙폭과대 되돌림' },
            { name: '기본', prob: 42, price: 287000, ret: 1.9, desc: '기술적 반등 — 3일 급락 후 데드캣 수준' },
            { name: '비관', prob: 33, price: 268000, ret: -4.8, desc: '유가 추가 급등·전쟁 확산 — 손절' },
          ],
          rationale: {
            summary: '3거래일간 약 -12% 급락(318,000→281,500)으로 단기 과매도 극단. 과거 삼성전자의 3일 연속 -4% 이상 급락 후 반등 확률이 높았던 패턴을 노리는 트레이드 — 단 중동 전쟁 리스크가 겹쳐 이전 배치보다 성공 확률을 낮게, 손절을 타이트하게 설정.',
            news: ['코스피 3일 연속 급락 — 7/8 -5.4% (7,246.79), 장중 7,000선 위협', '미·이란 재격화 — 호르무즈 상선 피격, 미군 타격, 유가 +5.2%', '삼성전자 281,500원 — 실적 쇼크 전(318,000원) 대비 -11.5%'],
            technical: ['RSI 극단적 과매도권 — 2년 내 최저 수준 근접', '275,000–280,000 심리적 지지 / 290,000 1차 저항', '거래량 폭증 — 셀링 클라이맥스 가능성'],
            fundamental: ['HBM4·파운드리 스토리는 불변 — 급락은 매크로(중동+AI 고점론) 요인', '증권가 목표가 대비 -44% 지점'],
          },
          riskFactors: ['밤사이 중동 확전 헤드라인(최대 변수)', '유가 $80 돌파 시 인플레·금리 공포 재점화', '외국인 3일 연속 순매도 지속 여부', '환율 급등(원화 약세) 리스크'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원', yieldPct: 0.51, next: '2026-08월 지급 예정', note: '당일 전략에선 배당 무관' },
          simId: 'b2-day-samsung',
        },
        {
          id: 'b2-day-nvda', ticker: 'NVDA', name: '엔비디아 (BofA 매수 반등)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'day', risk: 'high',
          refPrice: 196.93, refPriceAsOf: '2026-07-07 종가(달러) — 7/8 장중 변동 지속',
          buy:  { window: '2026-07-09 09:30–10:30 (미국 ET)', windowKst: '한국시간 7/9(목) 22:30–23:30', low: 189, high: 195, note: '중동發 리스크오프 갭하락 시 분할 매수. BofA "7년 최저 18배" 매수 유지가 하방 심리 지지. 갭상승 출발이면 관망.' },
          sell: { window: '2026-07-09 14:00–15:45 (미국 ET)', windowKst: '한국시간 7/10(금) 03:00–04:45', low: 198, high: 201, stop: 185, note: '당일 청산 원칙. $185 이탈 시 즉시 손절.' },
          expectedReturn: { base: 2.1, bull: 3.9, bear: -4.6 },
          scenarios: [
            { name: '낙관', prob: 27, price: 201, ret: 3.9, desc: '유가 안정 + AI 저가 매수 유입' },
            { name: '기본', prob: 43, price: 198.5, ret: 2.1, desc: '과매도 반등 — 저항 하단' },
            { name: '비관', prob: 30, price: 185, ret: -4.6, desc: '중동 확전 리스크오프 — 손절' },
          ],
          rationale: {
            summary: 'AI 고점론과 중동 리스크로 조정받는 구간에서 BofA가 "7년 최저 선행 PER 18배, 강화된 매수 기회"로 매수 의견을 재확인. 기관 매수 의견이 받치는 낙폭 구간의 당일 반등 트레이드.',
            news: ['BofA 매수 유지 — "EPS 디스카운트에 강하게 반대, 7년 최저 18배" (7/8)', '미·이란 재격화로 나스닥 -0.5% (7/8 장중) — 반도체 동반 약세', 'FOMC 의사록 발표 — 유가發 인플레 우려와 금리 경로 주목'],
            technical: ['$190–192 지지(7/7 저가 $190.63) / $198–201 저항', '5월 고점 $235 대비 -16% 조정 유지', '변동성 상승 국면 — 포지션 축소 권장'],
            fundamental: ['시총 $4.73T — AI 인프라 수요 구조 불변', '선행 PER 18배 — 밸류에이션 하단 논리'],
          },
          riskFactors: ['중동 확전·유가 급등(최대 변수)', 'FOMC 의사록 매파적 해석 시 금리 쇼크', 'AI 고점론 추가 확산', '반도체 섹터 수급 악화 지속'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당' },
          simId: 'b2-day-nvda',
        },
        {
          id: 'b2-day-xom', ticker: 'XOM', name: '엑슨모빌 (유가 급등 모멘텀)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'day', risk: 'mid',
          refPrice: 138.20, refPriceAsOf: '2026-07-07 종가(달러) — 7/8 유가 +5.2%로 장중 상승 가능성',
          buy:  { window: '2026-07-09 09:30–11:00 (미국 ET)', windowKst: '한국시간 7/9(목) 22:30–7/10 00:00', low: 137, high: 140.5, note: '유가 강세 지속 확인 후 눌림목 진입. 이미 +3% 이상 갭상승 출발이면 추격 금지.' },
          sell: { window: '2026-07-09 14:00–15:45 (미국 ET)', windowKst: '한국시간 7/10(금) 03:00–04:45', low: 141.5, high: 143.5, stop: 135, note: '당일 청산. 중동 완화 뉴스가 나오면 목표 미달이어도 즉시 정리(유가 급락 위험).' },
          expectedReturn: { base: 1.8, bull: 3.2, bear: -2.9 },
          scenarios: [
            { name: '낙관', prob: 30, price: 143.5, ret: 3.2, desc: '유가 $76+ 지속 — 에너지 섹터 주도' },
            { name: '기본', prob: 45, price: 141.5, ret: 1.8, desc: '유가 강세 유지 — 완만한 동반 상승' },
            { name: '비관', prob: 25, price: 135, ret: -2.9, desc: '중동 급완화 — 유가 반락, 손절' },
          ],
          rationale: {
            summary: '호르무즈 해협 긴장으로 WTI가 하루 +5.2%($74.16) 급등 — 미국 최대 석유기업 엑슨모빌이 가장 직접적인 수혜. 시장 전체가 하락하는 날에도 에너지 섹터만 오르는 "리스크오프의 피난처+수혜주" 이중 성격의 당일 트레이드.',
            news: ['WTI +5.2% $74.16 — 호르무즈 상선 피격·미군 타격 (7/8)', '트럼프 "미·이란 합의 종료" 선언 — 공급 차질 우려', '다우 -1.2% 하락장에서 에너지 섹터 상대 강세'],
            technical: ['52주 범위 $105.53–176.41의 중단 — 상승 여력', '$135–137 지지 / $142–144 저항', '유가와 동행성 높음 — 유가 차트가 곧 신호'],
            fundamental: ['배당 연 $4.12(수익률 3.0%), 42년 연속 증액', '저부채 우량 재무 — 유가 하락기에도 방어력'],
          },
          riskFactors: ['중동 급완화 시 유가 되돌림(당일 최대 변수)', '이미 갭상승 출발 시 추격 매수 위험', '전략비축유 방출 등 정책 개입 가능성'],
          dividend: { perShare: 1.03, currency: 'USD', frequency: '분기', schedule: '분기 $1.03 (연 $4.12) — 3·6·9·12월 지급', yieldPct: 3.02, next: '배당락 2026-08월 중순 예상', note: '42년 연속 배당 증액 — 장기 보유 전환도 고려 가능' },
          simId: 'b2-day-xom',
        },
        // ─────────────── 1주 ───────────────
        {
          id: 'b2-week-tsm', ticker: 'TSM', name: 'TSMC (실적 D-7)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'high',
          refPrice: 434.16, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-09–07-10 (미국 ET)', windowKst: '한국시간 7/9(목)–7/11(토) 새벽', low: 415, high: 432, note: '중동發 조정을 실적(7/16) 앞둔 저가 매수 기회로. 이전 배치보다 진입가를 낮춤 — 시장 전체가 흔들리는 중.' },
          sell: { window: '2026-07-15 14:00–16:00 (미국 ET)', windowKst: '한국시간 7/16(목) 03:00–05:00', low: 450, high: 460, stop: 405, note: '실적 발표 전 차익 실현 원칙 유지. 중동 리스크로 손절 라인을 $405로 하향 조정.' },
          expectedReturn: { base: 4.0, bull: 6.0, bear: -6.7 },
          scenarios: [
            { name: '낙관', prob: 28, price: 460, ret: 6.0, desc: '중동 완화 + 실적 기대 런업' },
            { name: '기본', prob: 42, price: 452, ret: 4.0, desc: '실적 앞 완만한 회복' },
            { name: '비관', prob: 30, price: 405, ret: -6.7, desc: '리스크오프 지속 — 손절' },
          ],
          rationale: {
            summary: '7/16 실적 발표(추정 EPS $3.80)를 앞둔 런업 전략은 유지하되, 중동 리스크로 성공 확률을 낮추고 손절을 타이트하게 재조정. AI 파운드리 독점 지위와 어닝 서프라이즈 이력이 하방을 방어.',
            news: ['2분기 실적 7/16 발표 확정 — D-7', '반도체 섹터 중동發 동반 조정 — 진입 단가 개선', 'AI 고점론 확산 중 — 실적이 반박 재료가 될지 주목'],
            technical: ['$415–425 지지 밴드 / $455–465 저항', '고점 $479 대비 -9~10% 조정 유지', '실적 전 주 평균 상승 경향(최근 8분기 중 6회)'],
            fundamental: ['3nm/2nm 독점 — AI 칩 수요 초과 지속', '대만 지정학 디스카운트에 중동 리스크 가산 국면'],
          },
          riskFactors: ['중동 확전 시 리스크오프 심화', '대만해협 이슈 동반 부각 가능성', '실적 가이던스 눈높이 부담', 'AI 고점론 — 좋은 실적에도 차익 매물 가능'],
          dividend: { perShare: 0.70, currency: 'USD', frequency: '분기', schedule: '분기 약 $0.70 (ADR)', yieldPct: 0.64, next: '2026-09월 예상', note: 'ADR 수수료·대만 원천세 유의' },
          simId: 'b2-week-tsm',
        },
        {
          id: 'b2-week-ko', ticker: 'KO', name: '코카콜라 (리스크오프 피난처)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'low',
          refPrice: 82.04, refPriceAsOf: '2026-06-30 종가(달러) — 7/8 방어주 강세로 상승 가능성',
          buy:  { window: '2026-07-09 09:30–16:00 (미국 ET)', windowKst: '한국시간 7/9(목) 22:30–7/10(금) 05:00', low: 81, high: 84, note: '전쟁 공포 장세의 전형적 피난처. $84 위면 이미 로테이션 반영 — 진입 매력 감소.' },
          sell: { window: '2026-07-16–07-17 (미국 ET)', windowKst: '한국시간 7/17(금)–7/18(토)', low: 85, high: 86.5, stop: 79, note: '중동 완화로 성장주 복귀 조짐이 보이면 조기 정리. 배당 매력으로 장기 전환도 무방.' },
          expectedReturn: { base: 2.4, bull: 4.2, bear: -3.7 },
          scenarios: [
            { name: '낙관', prob: 30, price: 86.5, ret: 4.2, desc: '리스크오프 심화 — 디펜시브 집중 매수' },
            { name: '기본', prob: 50, price: 84, ret: 2.4, desc: '방어주 로테이션 완만 지속' },
            { name: '비관', prob: 20, price: 79, ret: -3.7, desc: '급반전 랠리로 소외 — 손절' },
          ],
          rationale: {
            summary: '전쟁 공포 + 유가 급등 국면에서 자금이 몰리는 필수소비재 대장주. 하락장에서 오히려 오르는 성격(베타 0.5 이하)으로 1주 피난처 전략 — 시장이 무서울 때 강한 종목.',
            news: ['미·이란 재격화로 방어주 로테이션 가속 (7/8)', '유가發 인플레 우려 — 가격 전가력 있는 필수소비재 선호', '배당 64년 연속 증액 — 다음 배당락 9월 중순'],
            technical: ['$78–80 강한 지지 / $85 전고 저항', '변동성 연 14~15% — 급락장 방어력 검증', '하락장 상대강도(RS) 상위 섹터'],
            fundamental: ['글로벌 브랜드 가격 결정력 — 인플레 헤지 성격', '경기·전쟁과 무관한 수요(음료)'],
          },
          riskFactors: ['중동 급완화 시 성장주로 자금 회귀(소외)', '금리 상승 시 배당주 상대 매력 하락', '달러 강세 시 해외 매출 환산 감소'],
          dividend: { perShare: 0.53, currency: 'USD', frequency: '분기', schedule: '분기 $0.53 (연 $2.12) — 4·7·10·12월 지급', yieldPct: 2.56, next: '배당락 2026-09-11~15 예상', note: '1주 전략이지만 장기 보유 전환 가치 충분' },
          simId: 'b2-week-ko',
        },
        {
          id: 'b2-week-msft', ticker: 'MSFT', name: '마이크로소프트 (퀄리티 피난처)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'week', risk: 'mid',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러)',
          buy:  { window: '2026-07-09–07-10 (미국 ET)', windowKst: '한국시간 7/9(목)–7/11(토) 새벽', low: 375, high: 388, note: '리스크오프에 동반 하락 시 분할 매수 — 밸류에이션(21배)이 이미 바닥권이라 낙폭 제한 논리.' },
          sell: { window: '2026-07-16–07-17 (미국 ET)', windowKst: '한국시간 7/17(금)–7/18(토)', low: 397, high: 405, stop: 370, note: '1주 반등 목표. 7월 말 실적까지 홀딩 연장도 고려 가능(월간 전략과 연결).' },
          expectedReturn: { base: 3.4, bull: 5.5, bear: -4.3 },
          scenarios: [
            { name: '낙관', prob: 30, price: 405, ret: 5.5, desc: '퀄리티 선호 + 저가 매수 유입' },
            { name: '기본', prob: 45, price: 400, ret: 3.4, desc: '시장 안정화 동반 회복' },
            { name: '비관', prob: 25, price: 370, ret: -4.3, desc: '리스크오프 심화 — 손절' },
          ],
          rationale: {
            summary: '변동성 장세에서 대형 퀄리티 기술주는 "안전한 성장주" 역할. 2023년 이후 최저 밸류에이션(선행 21배) + 월가 목표가 $560이 하방을 받치는 가운데, 급락장 이후 1주 회복 구간을 노리는 전략.',
            news: ['월가 평균 목표가 $560 유지 — 현재가 대비 +45%', '유가發 인플레 우려에도 소프트웨어는 원가 영향 미미', '7월 말 FY26 4분기 실적 — 다음 촉매 대기'],
            technical: ['$373–378 이중바닥 지지 재확인 구간', '$397–405 갭 저항 — 1차 목표', '나스닥 대비 낮은 변동성(베타)'],
            fundamental: ['클라우드+AI 구조 성장 — 전쟁·유가와 무관한 수요', 'FCF 창출력 — 시장 스트레스 구간의 방어력'],
          },
          riskFactors: ['나스닥 전반 리스크오프 심화 시 동반 하락', 'FOMC 의사록·금리 경로 충격', 'AI capex 우려 재부각'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64)', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '1주 전략에선 배당 영향 미미' },
          simId: 'b2-week-msft',
        },
        // ─────────────── 1개월 ───────────────
        {
          id: 'b2-month-samsung', ticker: '005930.KS', name: '삼성전자 (이중 쇼크 회복)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'month', risk: 'mid',
          refPrice: 281500, refPriceAsOf: '2026-07-08 종가(원)',
          buy:  { window: '2026-07-09–07-16 분할 (한국 KST)', windowKst: '7/9(목)–7/16(목) 4회 분할', low: 265000, high: 285000, note: '실적 쇼크+중동 쇼크 이중 급락 구간을 4회 분할로 — 첫 배치보다 더 낮은 단가에 더 천천히.' },
          sell: { window: '2026-08-10–08-14 (한국 KST)', windowKst: '8월 10–14일', low: 310000, high: 322000, stop: 258000, note: '7월 말 확정실적 + 중동 안정화가 겹치면 목표 상향 여지. 258,000원 이탈 시 정리.' },
          expectedReturn: { base: 8.0, bull: 14.4, bear: -8.3 },
          scenarios: [
            { name: '낙관', prob: 28, price: 322000, ret: 14.4, desc: '중동 안정 + HBM4E 수주 공개' },
            { name: '기본', prob: 45, price: 305000, ret: 8.0, desc: '30만원대 회복 — 낙폭 절반 되돌림' },
            { name: '비관', prob: 27, price: 258000, ret: -8.3, desc: '전쟁 확산·메모리 피크아웃 — 손절' },
          ],
          rationale: {
            summary: '실적 쇼크(-6.9%)에 중동 쇼크(-4.9%)까지 겹쳐 3일간 -12% — 고점 대비 -15% 지점. 펀더멘털(HBM4E·목표가 50만원)과 무관한 매크로 급락분은 1개월 내 되돌림 확률이 높다는 판단. 이전 배치 대비 진입가를 15,000원 낮춤.',
            news: ['7/8 -4.9% 추가 급락 — 281,500원, 3일 누적 약 -12%', '시총 1위 자리 경쟁 구도 보도 — 수급 변동 심화', '7월 말 확정실적·컨콜 — HBM4E 수주 공개가 관건'],
            technical: ['272,000–280,000 지지 클러스터 / 300,000 저항', '주간 낙폭 2년 내 최대 — 과매도 극단', '월봉 추세는 아직 유지'],
            fundamental: ['HBM4 양산·HBM4E 샘플 — 기술 리더십 스토리 불변', '밸류에이션: 목표가 대비 -44%'],
          },
          riskFactors: ['중동 전쟁 장기화(신규 최대 변수)', '유가發 원가·환율 부담', '확정실적 부문별 부진 가능성', 'AI 고점론 — 외국인 이탈 지속'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원', yieldPct: 0.51, next: '2026-08월 지급 예정', note: '보유 기간 내 분기배당 1회 포함 예상' },
          simId: 'b2-month-samsung',
        },
        {
          id: 'b2-month-nvda', ticker: 'NVDA', name: '엔비디아 (18배 저점 매수)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'month', risk: 'high',
          refPrice: 196.93, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-09–07-15 분할 (미국 ET)', windowKst: '한국시간 7/9(목)–7/16(목) 분할', low: 185, high: 197, note: '중동 리스크오프로 밀릴 때마다 분할 — BofA "7년 최저 18배" 논리에 동의하는 저점 매수.' },
          sell: { window: '2026-08-05–08-12 (미국 ET)', windowKst: '8월 5–12일 (8월 말 실적 전 런업)', low: 210, high: 218, stop: 176, note: '8월 말 실적 기대감 정점 구간 분할 매도 전략 유지.' },
          expectedReturn: { base: 7.1, bull: 10.7, bear: -10.6 },
          scenarios: [
            { name: '낙관', prob: 28, price: 218, ret: 10.7, desc: '중동 안정 + 실적 런업 — $218' },
            { name: '기본', prob: 45, price: 211, ret: 7.1, desc: '조정 소화 후 완만한 회복' },
            { name: '비관', prob: 27, price: 176, ret: -10.6, desc: 'AI 고점론 + 전쟁 확산 — 손절' },
          ],
          rationale: {
            summary: 'AI 고점론과 중동 리스크가 만든 밸류에이션 바닥(선행 18배 — 7년 최저)에서 8월 말 실적 런업까지 1개월을 보는 전략. BofA 등 기관의 강한 매수 의견이 하방 심리를 방어.',
            news: ['BofA: "EPS 디스카운트에 강하게 반대 — 강화된 매수 기회" (7/8)', '시총 $4.73T — 고점 대비 조정에도 AI 수요 데이터 견조', '8월 말 FY27 2분기 실적 — 런업 계절성'],
            technical: ['$185–192 지지 클러스터 / $210 중간 저항', '고점 $235 대비 -16% — 되돌림 여지', '주봉 추세 유지 중'],
            fundamental: ['선행 PER 18배 — 7년 최저(BofA)', 'CUDA 생태계 해자 — 경쟁 심화에도 견고'],
          },
          riskFactors: ['중동 확전·유가 급등發 금리 공포', 'AI 고점론 확산 — 섹터 디레이팅', '8월 실적 눈높이', '빅테크 capex 가이던스 변화'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당' },
          simId: 'b2-month-nvda',
        },
        {
          id: 'b2-month-hynix', ticker: '000660.KS', name: 'SK하이닉스 (급락 후 재평가)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'month', risk: 'veryhigh',
          refPrice: 2201000, refPriceAsOf: '2026-07-07 종가(원) — 7/8 추가 하락 가능성, 주문 전 확인 필수',
          buy:  { window: '2026-07-09–07-17 분할 (한국 KST)', windowKst: '7/9(목)–7/17(금) 5회 분할', low: 1980000, high: 2150000, note: '고점(2,987,000) 대비 -30% 육박 폭락 구간 — 반드시 5회 이상 분할, 한 번에 사지 말 것. 이번 주 -9%대 하루 폭락 있었음.' },
          sell: { window: '2026-08-10–08-20 (한국 KST)', windowKst: '8월 중순', low: 2400000, high: 2550000, stop: 1950000, note: '나스닥 상장 계획·2분기 실적(7월 말)이 촉매. 1,950,000원 이탈 시 사이클 훼손으로 판단하고 정리.' },
          expectedReturn: { base: 11.3, bull: 15.9, bear: -11.4 },
          scenarios: [
            { name: '낙관', prob: 27, price: 2550000, ret: 15.9, desc: '나스닥 상장 재료 + HBM 수요 재확인' },
            { name: '기본', prob: 43, price: 2450000, ret: 11.3, desc: '낙폭 1/3 되돌림' },
            { name: '비관', prob: 30, price: 1950000, ret: -11.4, desc: 'AI 고점론 지속 — 손절' },
          ],
          rationale: {
            summary: '6/25 사상 최고가(2,987,000) 이후 2주 만에 -25% 이상 폭락 — 이번 주 하루 -9%대 급락과 서킷브레이커까지 겪은 극단 변동성 구간. 나스닥 상장 계획이라는 대형 재료와 HBM 독점 지위는 유효 — 극도로 위험하지만 보상도 큰 낙폭과대 재평가 베팅.',
            news: ['나스닥 상장 계획 보도 — 코스피 급등 재료였음 (7월 초)', '이번 주 반도체 폭락 — 하이닉스 하루 -9%대 기록', 'AI 고점론 vs HBM 공급 부족 — 시장 논쟁 격화'],
            technical: ['2,000,000 심리적 지지 / 2,450,000–2,550,000 저항', '고점 대비 -26% — 조정 폭 역대급', '변동성 연 55% 수준 — 극단 구간'],
            fundamental: ['HBM4 공급 주도권 — 삼성 대비 우위 유지', 'D램 가격 상승 사이클 지속 여부가 핵심'],
          },
          riskFactors: ['AI 고점론 — 섹터 전체 디레이팅 위험(최대)', '중동發 리스크오프 지속', '나스닥 상장 계획 무산·지연 가능성', '변동성 극대 — 손절 미준수 시 대형 손실'],
          dividend: { perShare: 1200, currency: 'KRW', frequency: '분기', schedule: '분기 고정 300원 + 실적연동', yieldPct: 0.05, next: '2026-08월 지급 예정', note: '성장주 — 배당 무의미' },
          simId: 'b2-month-hynix',
        },
        // ─────────────── 장기 (6–12개월) ───────────────
        {
          id: 'b2-long-msft', ticker: 'MSFT', name: '마이크로소프트 (장기)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러)',
          buy:  { window: '2026-07-09–09-30 매월 분할 (미국 ET)', windowKst: '7–9월 5회 분할 매수 (중동 변동성 활용)', low: 355, high: 395, note: '중동發 변동성으로 더 싸게 살 기회가 올 수 있음 — 분할 횟수를 4→5회로 확대.' },
          sell: { window: '2027-04월–07월 (미국 ET)', windowKst: '2027년 2분기 분할 매도', low: 480, high: 560, stop: 330, note: '월가 목표 $560 접근 시 단계적 실현 — 전략 유지.' },
          expectedReturn: { base: 15.1, bull: 34.5, bear: -14.7 },
          scenarios: [
            { name: '낙관', prob: 35, price: 520, ret: 34.5, desc: 'AI capex 수익화 입증' },
            { name: '기본', prob: 45, price: 460, ret: 18.9, desc: '멀티플 정상화' },
            { name: '비관', prob: 20, price: 330, ret: -14.7, desc: 'AI 투자 회수 지연 장기화' },
          ],
          rationale: {
            summary: '전쟁·유가·AI 고점론 어느 것도 12개월 뒤 마이크로소프트의 현금창출력을 바꾸지 못한다 — 장기 논리는 이전 배치와 동일하며, 오히려 변동성이 커질수록 분할 매수 단가가 좋아진다. 2023년 이후 최저 밸류에이션 유지 중.',
            news: ['월가 평균 목표가 $560 — 컨센서스 강력 매수 유지', '중동 변동성 — 장기 투자자에겐 진입 기회', 'Copilot·Azure AI 매출 기여 확대 중'],
            technical: ['$373 이중바닥 — 장기 지지 구축', '월봉 장기 상승 구조 불변'],
            fundamental: ['클라우드+오피스+AI 삼중 해자', '배당 21년 연속 증액 — 연 $3.64'],
          },
          riskFactors: ['AI 투자 회수 속도', '반독점 규제', '환율(원화 기준)', '경기 침체 시 IT 지출 둔화'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64) — 9·12·3·6월 지급', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '12개월 보유 시 4회 수령' },
          simId: 'b2-long-msft',
        },
        {
          id: 'b2-long-ko', ticker: 'KO', name: '코카콜라 (배당 코어)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 82.04, refPriceAsOf: '2026-06-30 종가(달러)',
          buy:  { window: '2026-07-09–09-10 분할 (미국 ET)', windowKst: '7–9월 초 분할 (9월 중순 배당락 전 완료)', low: 78, high: 84, note: '전쟁 공포 장세로 단기 프리미엄이 붙을 수 있음 — $84 위에선 매수 속도 조절.' },
          sell: { window: '2027-07월 이후 검토', windowKst: '원칙적 장기 보유', low: 90, high: 95, stop: 72, note: '배당 수령이 주목적 — 전략 유지.' },
          expectedReturn: { base: 7.4, bull: 15.8, bear: -12.2 },
          scenarios: [
            { name: '낙관', prob: 32, price: 95, ret: 15.8, desc: '디펜시브 선호 장기화 + 배당 성장' },
            { name: '기본', prob: 48, price: 88, ret: 7.3, desc: '완만한 우상향 + 배당 2.6%' },
            { name: '비관', prob: 20, price: 72, ret: -12.2, desc: '소비 둔화 — 손절 기준' },
          ],
          rationale: {
            summary: '중동 전쟁 리스크가 부각될수록 빛나는 64년 연속 배당 증액 배당왕 — 이번 갱신에서 유일하게 "환경이 좋아진" 장기 종목. 9월 중순 배당락 전 매집 완료 전략 유지.',
            news: ['리스크오프 국면 디펜시브 로테이션 수혜 (7/8)', '차기 배당락 9/11–15 예상 — 매수 데드라인', '유가發 인플레 — 가격 전가력 보유 기업 선호'],
            technical: ['$78–80 장기 지지 / $85 저항', '하락장 상대강도 상위 — 방어력 검증 중'],
            fundamental: ['배당 64년 연속 증액 — 전쟁·경기와 무관', '글로벌 브랜드 가격 결정력'],
          },
          riskFactors: ['금리 재상승 시 배당주 매력 하락', '탄산 수요 둔화 트렌드', '달러 강세 시 환산 손실', '환율(원화 기준)'],
          dividend: { perShare: 0.53, currency: 'USD', frequency: '분기', schedule: '분기 $0.53 (연 $2.12) — 4·7·10·12월 지급', yieldPct: 2.56, next: '배당락 2026-09-11~15 예상, 지급 10/1', note: '12개월 4회 수령, 주당 연 $2.12 (세전)' },
          simId: 'b2-long-ko',
        },
        {
          id: 'b2-long-samsung', ticker: '005930.KS', name: '삼성전자 (장기 — 더 싸졌다)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'long', risk: 'mid',
          refPrice: 281500, refPriceAsOf: '2026-07-08 종가(원)',
          buy:  { window: '2026-07-09–10-30 매월 분할 (한국 KST)', windowKst: '7–10월 8회 분할 매수 (기간·횟수 확대)', low: 255000, high: 290000, note: '이중 쇼크로 첫 배치보다 -5% 싸진 가격 — 분할 기간을 3개월→4개월, 6회→8회로 늘려 변동성을 흡수.' },
          sell: { window: '2027-04월–07월 (한국 KST)', windowKst: '2027년 2분기 분할 매도', low: 400000, high: 450000, stop: 228000, note: '증권가 목표 50만원 대비 -44% 지점에서 시작하는 장기 포지션. 228,000원 이탈 시 사이클 논리 재점검.' },
          expectedReturn: { base: 14.7, bull: 49.2, bear: -19.0 },
          scenarios: [
            { name: '낙관', prob: 30, price: 420000, ret: 49.2, desc: 'HBM 점유율 회복 + 중동 안정' },
            { name: '기본', prob: 45, price: 360000, ret: 27.9, desc: '메모리 사이클 지속 — 쇼크 전 회복' },
            { name: '비관', prob: 25, price: 228000, ret: -19.0, desc: '사이클 피크아웃 확인 — 손절' },
          ],
          rationale: {
            summary: '실적 쇼크+중동 쇼크로 3일 만에 -12% — 장기 투자자 관점에선 같은 회사를 더 싸게 사는 기회. HBM4E 기술 리더십과 증권가 목표 50만원은 그대로인데 가격만 281,500원이 됐다. 분할 매수 기간을 늘려 전쟁 변동성까지 흡수하는 설계.',
            news: ['3일 누적 -12% — 고점 대비 -15% 지점', '증권가 목표 500,000원 유지 — 괴리 -44%', 'HBM4E 슈퍼사이클 — AI 서버 투자 구조 지속'],
            technical: ['255,000–270,000 장기 지지 밴드 접근', '월봉 추세 유지 — 급락은 추세 내 조정', '과매도 극단 — 장기 진입 신호 구간'],
            fundamental: ['메모리+파운드리+모바일 복합 포트폴리오', '분기배당 연 1,444원 — 기다림의 보상', 'HBM 점유율 회복이 리레이팅 핵심'],
          },
          riskFactors: ['중동 전쟁 장기화 — 글로벌 수요 둔화', '메모리 사이클 피크아웃 시점', 'HBM 경쟁 심화', '환율·외국인 수급'],
          dividend: { perShare: 1444, currency: 'KRW', frequency: '분기', schedule: '분기 361원 × 4회 = 연 1,444원', yieldPct: 0.51, next: '2026-08월 지급 예정', note: '12개월 4회 수령, 15.4% 원천징수 후 실수령' },
          simId: 'b2-long-samsung',
        },
      ],
    },
    {
      id: 'batch-2026-07-08',
      generatedAt: '2026-07-08T19:45+09:00',
      title: '2026-07-08 추천 (반도체 급락 국면)',
      marketSnapshot:
        'S&P 500 7,537.43 (7/6), 나스닥 26,121.16 (7/6). 7/7 삼성전자 2분기 잠정실적 실망으로 반도체 급락 — 필라델피아 반도체지수(SOX) 이틀간 -12%, 나스닥 -1.16%. 삼성전자 296,000원(-6.92%). 원/달러 환율 약 1,528원. TSMC 실적 7/16, 테슬라 실적 7/22 예정. 증권가 S&P 연말 목표 7,100(현 수준 대비 -5%) — 과열 경계 병존.',
      picks: [
        // ─────────────── 당일 ───────────────
        {
          id: 'day-nvda', ticker: 'NVDA', name: '엔비디아', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'day', risk: 'high',
          refPrice: 195.55, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-08 09:30–10:30 (미국 ET)', windowKst: '한국시간 7/8(수) 22:30–23:30', low: 191, high: 194.5, note: '개장 직후 반도체 투매 연장으로 밀릴 때 지정가 분할 매수. 195 이상 추격 매수 금지.' },
          sell: { window: '2026-07-08 14:00–15:45 (미국 ET)', windowKst: '한국시간 7/9(목) 03:00–04:45', low: 197, high: 199, stop: 188, note: '198–203은 기술적 저항 구간 — 197 도달 시 절반, 199 접근 시 전량 정리. 188 이탈 시 즉시 손절.' },
          expectedReturn: { base: 1.8, bull: 3.6, bear: -3.3 },
          scenarios: [
            { name: '낙관', prob: 30, price: 199, ret: 3.6, desc: '과매도 반등이 저항 상단까지 연장' },
            { name: '기본', prob: 45, price: 197, ret: 1.8, desc: '낙폭 일부 되돌림, 저항 하단 도달' },
            { name: '비관', prob: 25, price: 188, ret: -3.3, desc: '반도체 투매 연장 — 손절 집행' },
          ],
          rationale: {
            summary: 'SOX 이틀 -12% 급락으로 과매도권 진입. 엔비디아는 펀더멘털 훼손 없이 삼성 실적 쇼크에 동반 하락 — 골드만삭스는 선행 PER 21.7배를 "매력적"이라 평가. 당일 기술적 반등을 노리는 단기 트레이드.',
            news: ['7/7 삼성 실적 쇼크로 반도체 섹터 급락(SOX 2일 -12%) — 개별 악재 아닌 섹터 투매', '골드만삭스: Kyber 지연설 부인 후 21.7배 밸류에이션 "compelling" 평가', '시총 $4.84T 유지 — AI 인프라 수요 견조'],
            technical: ['52주 범위 $157.34–236.54의 중하단, 5월 고점($235.47) 대비 -17%', '$198–203 저항 / $188–190 단기 지지', 'RSI 과매도권 근접 — 반등 탄력 구간'],
            fundamental: ['AI 데이터센터 GPU 수요 지속, 수주 잔고 견조', '선행 PER 21.7배 — 최근 3년 밴드 하단'],
          },
          riskFactors: ['반도체 투매 3일차 연장 가능성', '중동 정세·유가에 따른 리스크오프', '개장 갭 방향(갭하락 시에만 진입 유효)', '미 국채 금리 급등 여부'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당 — 배당 목적 부적합' },
          simId: 'day-nvda',
        },
        {
          id: 'day-samsung', ticker: '005930.KS', name: '삼성전자', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'day', risk: 'mid',
          refPrice: 296000, refPriceAsOf: '2026-07-07 종가(원)',
          buy:  { window: '2026-07-09 09:00–09:40 (한국 KST)', windowKst: '7/9(목) 09:00–09:40', low: 287000, high: 293000, note: '전일 -6.92% 급락 후 개장 추가 하락 시 분할 매수. 295,000원 위 시초가 갭상승 출발이면 진입 보류.' },
          sell: { window: '2026-07-09 14:30–15:20 (한국 KST)', windowKst: '7/9(목) 14:30–15:20', low: 299000, high: 304000, stop: 283000, note: '장 마감 전 전량 정리(당일 전략). 283,000원 이탈 시 손절.' },
          expectedReturn: { base: 2.1, bull: 3.8, bear: -3.4 },
          scenarios: [
            { name: '낙관', prob: 28, price: 304000, ret: 3.8, desc: '낙폭과대 인식 + 기관 저가 매수 유입' },
            { name: '기본', prob: 47, price: 300000, ret: 2.1, desc: '30만원 회복 시도 수준의 기술적 반등' },
            { name: '비관', prob: 25, price: 283000, ret: -3.4, desc: '실적 쇼크 여진 지속 — 손절 집행' },
          ],
          rationale: {
            summary: '7/7 2분기 잠정실적이 컨센서스(영업이익 86~100조원)에 못 미치며 하루 -6.92% 급락. 과거 삼성전자의 실적 쇼크 당일 급락은 다음 거래일 기술적 반등이 잦았던 패턴 — 낙폭과대 단기 반등 트레이드.',
            news: ['7/7 2분기 잠정실적 발표 — 컨센서스 하회로 -6.92% (296,000원)', '증권가 목표주가 최고 500,000원 유지 — 중장기 시각 불변', 'HBM4 세계 최초 양산(2월) + HBM4E 12단 샘플 출하 완료'],
            technical: ['일간 -6.92%는 최근 2년 내 최대급 낙폭 — 단기 과매도', '심리적 지지 285,000–290,000 / 저항 300,000(라운드넘버)', '거래량 급증 동반 하락 → 단기 셀링 클라이맥스 가능성'],
            fundamental: ['HBM4E·파운드리 수주 모멘텀은 유효 — 쇼크는 일회성 비용 요인 분석 우세', '반도체 슈퍼사이클 구조는 훼손되지 않음'],
          },
          riskFactors: ['외국인 프로그램 매도 연장 여부', '실적 세부(부문별) 공시 전 불확실성', '환율 1,550원 돌파 시 외국인 수급 악화', '미 반도체 섹터 야간 흐름(7/8 미국장)'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원 (5·8·11월·익년 4월 지급)', yieldPct: 0.49, next: '2026-08월 지급 예정', note: '주주환원 정책상 분기 균등 배당' },
          simId: 'day-samsung',
        },
        {
          id: 'day-tsla', ticker: 'TSLA', name: '테슬라', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'day', risk: 'veryhigh',
          refPrice: 402.90, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-08 09:30–11:00 (미국 ET)', windowKst: '한국시간 7/8(수) 22:30–7/9 00:00', low: 396, high: 401, note: '전일 -4% 조정을 로보택시 모멘텀 눌림목으로 활용. 402 위 출발 시 진입 보류.' },
          sell: { window: '2026-07-08 14:00–15:45 (미국 ET)', windowKst: '한국시간 7/9(목) 03:00–04:45', low: 410, high: 415, stop: 389, note: '변동성 극대 종목 — 목표가 도달 즉시 기계적 청산. 389 이탈 시 손절.' },
          expectedReturn: { base: 2.3, bull: 3.8, bear: -3.2 },
          scenarios: [
            { name: '낙관', prob: 27, price: 415, ret: 3.8, desc: '로보택시 헤드라인 재점화로 강반등' },
            { name: '기본', prob: 43, price: 410, ret: 2.3, desc: '전일 급락분 절반 되돌림' },
            { name: '비관', prob: 30, price: 389, ret: -3.2, desc: '고밸류 부담 매물 연장 — 손절' },
          ],
          rationale: {
            summary: '2분기 인도량 480,126대(컨센서스 +18% 상회), 7/5 마이애미 로보택시 서비스 개시(2번째 도시), 유럽 등록대수 +57% 등 모멘텀 재료가 겹겹인 가운데 7/7 -4.02% 조정 — 뉴스 모멘텀 눌림목 데이트레이드.',
            news: ['7/5 마이애미 로보택시 개시 — 오스틴 이어 2번째, 사이버캡 테스트 시작', '2분기 인도 480,126대 — 컨센서스(406,024대) +18% 상회', '유럽 1–5월 등록 118,068대(+57.2% YoY)', '실적 발표 7/22 예정 — 기대감 유입 구간'],
            technical: ['$370대 중반 → $420 상승 후 되돌림 — 상승 추세 유지', '$416 저항 / $393–396 지지', '일중 변동성 연 62% 수준 — 데이트레이드 적합'],
            fundamental: ['선행 PER 204배 — 밸류에이션 부담이 상시 변동성 요인', '로보택시·에너지 사업 확장이 멀티플 방어'],
          },
          riskFactors: ['고밸류에이션 — 악재에 민감', '일론 머스크 발언 리스크', 'BYD 등 경쟁 심화 헤드라인', '로보택시 사고·규제 뉴스 발생 가능성'],
          dividend: null,
          simId: 'day-tsla',
        },
        // ─────────────── 1주 ───────────────
        {
          id: 'week-tsm', ticker: 'TSM', name: 'TSMC (ADR)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'week', risk: 'mid',
          refPrice: 434.16, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-08–07-09 09:30–16:00 (미국 ET)', windowKst: '한국시간 7/8(수) 밤–7/10(금) 새벽', low: 425, high: 438, note: '실적(7/16) 앞둔 런업 전략 — 이틀에 걸쳐 분할 매수.' },
          sell: { window: '2026-07-15 14:00–16:00 (미국 ET)', windowKst: '한국시간 7/16(목) 03:00–05:00', low: 452, high: 460, stop: 415, note: '기본 전략은 실적 발표(7/16) 전 차익 실현 — 이벤트 리스크 회피. 강세 지속 시 절반만 실적 홀딩 가능(고위험).' },
          expectedReturn: { base: 4.3, bull: 6.0, bear: -4.4 },
          scenarios: [
            { name: '낙관', prob: 32, price: 460, ret: 6.0, desc: '실적 기대 런업 + 반도체 반등 동반' },
            { name: '기본', prob: 43, price: 452, ret: 4.3, desc: '실적 전 완만한 기대감 랠리' },
            { name: '비관', prob: 25, price: 415, ret: -4.4, desc: '섹터 투매 연장 — 손절' },
          ],
          rationale: {
            summary: '7/16 2분기 실적 발표(추정 EPS $3.80, 매출 $39.8B)를 앞둔 프리어닝 런업 전략. AI 파운드리 독점 지위로 어닝 서프라이즈 이력 풍부 — 발표 직전 매도로 이벤트 리스크를 제거하는 것이 기본형.',
            news: ['2분기 실적 7/16 14:00(대만) 발표 확정', '추정 EPS $3.80 / 매출 $39.82B — AI 수주 반영 상향 추세', '삼성 쇼크발 섹터 조정으로 진입 단가 매력 상승'],
            technical: ['52주 범위 $223.70–479.00 — 고점 대비 -9% 조정', '$425–430 지지 / $455–465 저항', '실적 전 5거래일 평균 상승 경향(최근 8개 분기 중 6회)'],
            fundamental: ['3nm/2nm 선단공정 독점적 지위, AI 칩 파운드리 수요 초과', '시총 $2.34T — 대만 지정학 디스카운트 병존'],
          },
          riskFactors: ['대만해협 지정학 헤드라인', '실적 가이던스 눈높이(이미 높음)', '섹터 투매 연장 시 런업 실패', 'ADR 프리미엄 변동'],
          dividend: { perShare: 0.70, currency: 'USD', frequency: '분기', schedule: '분기 약 $0.70 (ADR 기준, 대만 원천세 21% 차감 전)', yieldPct: 0.64, next: '2026-09월 예상', note: 'ADR 수수료·대만 원천세로 실수령 변동' },
          simId: 'week-tsm',
        },
        {
          id: 'week-hynix', ticker: '000660.KS', name: 'SK하이닉스', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'week', risk: 'high',
          refPrice: 2870000, refPriceAsOf: '2026-07-07 종가(원) 부근',
          buy:  { window: '2026-07-09–07-10 09:00–11:00 (한국 KST)', windowKst: '7/9(목)–7/10(금) 오전', low: 2750000, high: 2850000, note: '삼성 쇼크 동반 조정을 HBM 대장주 저가 매수 기회로 — 이틀 분할 매수.' },
          sell: { window: '2026-07-15–07-16 13:00–15:20 (한국 KST)', windowKst: '7/15(수)–7/16(목) 오후', low: 2950000, high: 3000000, stop: 2650000, note: 'TSMC 실적(7/16)발 반도체 심리 개선 구간에서 차익 실현. 전고점(2,987,000원) 부근 저항 유의.' },
          expectedReturn: { base: 5.4, bull: 7.1, bear: -5.4 },
          scenarios: [
            { name: '낙관', prob: 30, price: 3000000, ret: 7.1, desc: '사상 최고가 재도전 — 300만원 터치' },
            { name: '기본', prob: 45, price: 2950000, ret: 5.4, desc: 'HBM 수급 재확인 반등' },
            { name: '비관', prob: 25, price: 2650000, ret: -5.4, desc: '메모리 업황 우려 확산 — 손절' },
          ],
          rationale: {
            summary: '삼성 실적 쇼크로 동반 조정됐지만 HBM 공급 지위는 별개 — 6/25 사상 최고가(2,987,000원) 경신 직후의 건전한 조정. 증권가 목표가 300만원. TSMC 실적(7/16)이 AI 수요를 재확인하면 1주 내 되돌림 시나리오.',
            news: ['6/25 사상 최고가 2,987,000원 기록 후 조정', '증권가 목표주가 300만원 제시 — HBM·D램 가격 상승 반영', '삼성 쇼크와의 차별화: HBM4 공급 주도권 유지'],
            technical: ['2,750,000–2,800,000 지지(전 돌파 구간) / 2,987,000 저항', '상승 추세선 유지 — 조정폭 -4~5%는 추세 내 눌림', '외국인 순매수 기조 지속'],
            fundamental: ['AI 서버 투자 확대 — HBM 수요 초과 지속', 'D램·낸드 동반 가격 상승 사이클'],
          },
          riskFactors: ['삼성 실적 세부 발표 후 메모리 업황 재평가', '고점 부근 차익 매물', '환율 급등 시 외국인 이탈', '미 반도체 관세·수출규제 헤드라인'],
          dividend: { perShare: 1200, currency: 'KRW', frequency: '분기', schedule: '분기 고정 300원 + 연간 실적연동 — 연 1,200원 내외', yieldPct: 0.04, next: '2026-08월 지급 예정', note: '성장주 성격 — 배당 비중 낮음' },
          simId: 'week-hynix',
        },
        {
          id: 'week-tsla', ticker: 'TSLA', name: '테슬라 (실적 런업)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'week', risk: 'veryhigh',
          refPrice: 402.90, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-09 09:30–16:00 (미국 ET)', windowKst: '한국시간 7/9(목) 22:30–7/10(금) 05:00', low: 395, high: 405, note: '실적(7/22) 앞둔 기대감 런업 진입.' },
          sell: { window: '2026-07-17 14:00–16:00 (미국 ET)', windowKst: '한국시간 7/18(토) 03:00–05:00', low: 420, high: 428, stop: 382, note: '실적 발표 전주 금요일 정리 — 실적 자체는 베팅하지 않음(이벤트 리스크 회피).' },
          expectedReturn: { base: 4.2, bull: 6.2, bear: -5.2 },
          scenarios: [
            { name: '낙관', prob: 30, price: 428, ret: 6.2, desc: '로보택시 확장 + 인도량 서프라이즈 재평가' },
            { name: '기본', prob: 40, price: 420, ret: 4.2, desc: '$416 저항 돌파 시도 런업' },
            { name: '비관', prob: 30, price: 382, ret: -5.2, desc: '고밸류 매물 + 시장 조정 동반 — 손절' },
          ],
          rationale: {
            summary: '2분기 인도량 +18% 서프라이즈와 마이애미 로보택시 개시 이후, 7/22 실적 발표를 앞둔 열흘간의 기대감 런업을 노리는 전략. 발표 전 청산으로 어닝 변동성은 취하지 않음.',
            news: ['실적 발표 7/22 확정 — 런업 구간 진입', '인도량 서프라이즈(+18%)로 매출 추정치 상향 중', '마이애미 로보택시 — 도시 확장 로드맵 주목'],
            technical: ['$416(직전 고점) 돌파 시 $430대 열림', '$393–396 1차 지지, $382 추세 지지', '연 변동성 62% — 포지션 소액 권장'],
            fundamental: ['로보택시·FSD 구독 매출 성장 스토리', 'PER 204배 — 실적 미스 시 급락 위험 상존'],
          },
          riskFactors: ['실적 프리뷰 하향 리포트 리스크', '머스크 리스크(발언·정치)', '나스닥 조정 시 고베타 급락', '로보택시 규제 이슈'],
          dividend: null,
          simId: 'week-tsla',
        },
        // ─────────────── 1개월 ───────────────
        {
          id: 'month-msft', ticker: 'MSFT', name: '마이크로소프트', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'month', risk: 'mid',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러)',
          buy:  { window: '2026-07-08–07-10 09:30–16:00 (미국 ET) 분할', windowKst: '한국시간 7/8(수)–7/11(토) 3회 분할', low: 378, high: 390, note: '3회 분할 매수 — 조정 시 $378까지 추가 매수.' },
          sell: { window: '2026-08-06–08-10 (미국 ET)', windowKst: '8월 6–10일 (실적 발표 소화 후)', low: 408, high: 420, stop: 362, note: '7월 말 FY26 4분기 실적이 촉매 — 발표 후 갭 소화 구간에서 분할 매도.' },
          expectedReturn: { base: 6.5, bull: 8.6, bear: -6.4 },
          scenarios: [
            { name: '낙관', prob: 33, price: 420, ret: 8.6, desc: 'Azure 재가속 확인 — 멀티플 회복' },
            { name: '기본', prob: 42, price: 410, ret: 6.0, desc: '밸류에이션 매력 유입 완만 회복' },
            { name: '비관', prob: 25, price: 362, ret: -6.4, desc: 'AI capex 우려 재부각 — 손절' },
          ],
          rationale: {
            summary: '52주 고점 $555 대비 -30%, 선행 PER 21~22배로 2023년 이후 최저 밸류에이션. 애널리스트 97명 컨센서스 "강력 매수", 평균 목표가 $560. 7월 말 실적에서 Azure 성장 재확인 시 1개월 내 $410대 회복 시나리오.',
            news: ['월가 평균 목표주가 $560 — 현재가 대비 +45%', 'AI capex $190B 계획과 4,800명 감원이 단기 불확실성', '펀더멘털과 주가 괴리 — "희귀한 진입 기회" 평가 다수'],
            technical: ['3월 저점 $373 이중바닥 지지 확인', '$362 이탈 시 추세 훼손(손절 기준)', '$405–410 갭 저항 — 1차 목표'],
            fundamental: ['선행 PER 21~22배 — 2023년 이후 최저', 'Azure·Copilot 매출 성장 지속, FY26 실적 가이던스 주목'],
          },
          riskFactors: ['7월 말 실적 발표 — Azure 성장률이 관건', 'AI capex 추가 증액 발표 시 마진 우려', '금리·나스닥 밸류에이션 조정', '감원 관련 조직 리스크'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64) — 9·12·3·6월 지급', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '보유 기간 내 배당락 1회 포함 가능' },
          simId: 'month-msft',
        },
        {
          id: 'month-samsung', ticker: '005930.KS', name: '삼성전자 (쇼크 회복)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'month', risk: 'mid',
          refPrice: 296000, refPriceAsOf: '2026-07-07 종가(원)',
          buy:  { window: '2026-07-09–07-15 09:00–15:20 (한국 KST) 분할', windowKst: '7/9(목)–7/15(수) 3회 분할', low: 285000, high: 296000, note: '실적 쇼크 소화 구간 1주에 걸쳐 3회 분할 매수.' },
          sell: { window: '2026-08-10–08-14 (한국 KST)', windowKst: '8월 10–14일', low: 318000, high: 330000, stop: 272000, note: '7월 말 확정실적·컨퍼런스콜에서 HBM4E 수주 확인 시 목표 상향 여지.' },
          expectedReturn: { base: 8.1, bull: 11.5, bear: -8.1 },
          scenarios: [
            { name: '낙관', prob: 30, price: 330000, ret: 11.5, desc: 'HBM4E 수주 공개 + 외국인 복귀' },
            { name: '기본', prob: 45, price: 320000, ret: 8.1, desc: '쇼크 전 가격대(318,000원) 회복' },
            { name: '비관', prob: 25, price: 272000, ret: -8.1, desc: '메모리 가격 피크아웃 우려 — 손절' },
          ],
          rationale: {
            summary: '실적 쇼크 -6.92%로 쇼크 전 318,000원 대비 큰 갭 발생. HBM4 양산·HBM4E 샘플 출하라는 구조적 모멘텀은 유효 — 증권가 목표가 최고 50만원. 1개월 내 쇼크 전 가격 회복을 기본 시나리오로 설정.',
            news: ['증권가 목표주가 최고 500,000원 — 쇼크 후에도 유지', 'HBM4 세계 최초 양산(2월), HBM4E 12단 샘플 3개월 만에 출하', '7월 말 확정실적 발표 — 부문별 실적·컨콜이 2차 촉매'],
            technical: ['갭하락 구간 296,000→318,000 — 갭 메우기 목표', '285,000 지지선(60일선 부근) / 272,000 추세 지지', '낙폭과대 구간 — 수급 개선 시 복원력 높음'],
            fundamental: ['HBM 시장 점유율 회복 스토리 — 밸류에이션 리레이팅 여지', '파운드리 2nm 수주 모멘텀'],
          },
          riskFactors: ['확정실적에서 부문별 부진 확인 가능성', 'D램 현물가 흐름', '환율·외국인 수급', '미·중 반도체 규제 변수'],
          dividend: { perShare: 361, currency: 'KRW', frequency: '분기', schedule: '분기 361원, 연 1,444원 (5·8·11월·익년 4월 지급)', yieldPct: 0.49, next: '2026-08월 지급 예정', note: '보유 기간 내 분기배당 1회 포함 예상' },
          simId: 'month-samsung',
        },
        {
          id: 'month-nvda', ticker: 'NVDA', name: '엔비디아 (실적 런업)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'month', risk: 'high',
          refPrice: 195.55, refPriceAsOf: '2026-07-07 종가(달러)',
          buy:  { window: '2026-07-08–07-14 09:30–16:00 (미국 ET) 분할', windowKst: '한국시간 7/8(수)–7/15(수) 분할', low: 188, high: 196, note: '조정 구간 분할 매수 — $188 접근 시 비중 확대.' },
          sell: { window: '2026-08-05–08-12 (미국 ET)', windowKst: '8월 5–12일 (8월 말 실적 전 런업 구간)', low: 210, high: 218, stop: 178, note: '8월 말 실적 발표 전 기대감 정점 구간에서 분할 매도.' },
          expectedReturn: { base: 7.4, bull: 11.5, bear: -9.0 },
          scenarios: [
            { name: '낙관', prob: 30, price: 218, ret: 11.5, desc: '섹터 회복 + 실적 기대 랠리로 $218' },
            { name: '기본', prob: 45, price: 210, ret: 7.4, desc: '조정 회복 후 완만한 런업' },
            { name: '비관', prob: 25, price: 178, ret: -9.0, desc: 'AI 과열론 확산 조정 — 손절' },
          ],
          rationale: {
            summary: '섹터 급락으로 열린 진입 기회 + 8월 말 실적 발표 전 런업이라는 계절적 패턴 결합. 골드만삭스 밸류에이션 매력 평가와 $4.84T 시총이 받치는 AI 대장주 — 1개월 보유로 조정 회복분과 런업 초입을 함께 취하는 전략.',
            news: ['골드만: 21.7배 "compelling" — Kyber 지연설 부인', '8월 말 2분기(FY27) 실적 발표 예정 — 런업 계절성', 'AI 데이터센터 투자 사이클 지속 확인 중'],
            technical: ['5월 고점 $235 대비 -17% 조정 — 되돌림 여지', '$188–190 지지 / $210 중간 저항 / $220 갭 저항', '주봉 상승 추세 유지'],
            fundamental: ['데이터센터 매출 비중 압도적 — AI 수요 직결', '경쟁 심화에도 CUDA 생태계 해자 견고'],
          },
          riskFactors: ['S&P 연말 목표 7,100(-5%) 등 과열 경고 — 지수 조정 위험', '빅테크 capex 가이던스 변화', '중국 수출 규제 뉴스', '8월 실적 눈높이 과열 여부'],
          dividend: { perShare: 0.01, currency: 'USD', frequency: '분기', schedule: '3·6·9·12월 지급', yieldPct: 0.02, next: '2026-09월 예상', note: '상징적 배당' },
          simId: 'month-nvda',
        },
        // ─────────────── 장기 (6–12개월) ───────────────
        {
          id: 'long-msft', ticker: 'MSFT', name: '마이크로소프트 (장기)', market: 'US', exchange: 'NASDAQ', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 386.74, refPriceAsOf: '2026-07-06 종가(달러)',
          buy:  { window: '2026-07-08–08-29 매월 분할 (미국 ET)', windowKst: '7–8월 중 4회 분할 매수', low: 360, high: 395, note: '적립식 4회 분할 — 조정 시 매수 단가 하향.' },
          sell: { window: '2027-04-01–07-01 (미국 ET)', windowKst: '2027년 2분기 중 분할 매도', low: 480, high: 560, stop: 330, note: '12개월 목표 — 월가 평균 목표가 $560 접근 시 단계적 차익 실현. $330 이탈 시 논리 훼손으로 정리.' },
          expectedReturn: { base: 15.2, bull: 34.5, bear: -14.7 },
          scenarios: [
            { name: '낙관', prob: 35, price: 520, ret: 34.5, desc: 'AI capex 수익화 입증 — 목표가 수렴' },
            { name: '기본', prob: 45, price: 460, ret: 18.9, desc: '멀티플 정상화(25배) 회복' },
            { name: '비관', prob: 20, price: 330, ret: -14.7, desc: 'AI 투자 회수 지연 장기화' },
          ],
          rationale: {
            summary: '2023년 이후 최저 밸류에이션(선행 21~22배)에서 사는 빅테크 코어 자산. AI capex $190B가 FY27부터 매출로 회수되는 구간이 12개월 안에 도래 — 월가 97명 평균 목표가 $560. 배당 성장(연 $3.64)까지 겸비한 장기 포지션.',
            news: ['평균 목표가 $560 (+45%) — 컨센서스 강력 매수', 'AI capex 우려로 조정 — 장기 투자자에게 진입 기회라는 평가 다수', 'Copilot·Azure AI 매출 기여 확대 중'],
            technical: ['$373 이중바닥 — 장기 지지 구축', '월봉 기준 200월선 위 장기 상승 구조 유지'],
            fundamental: ['클라우드+오피스+AI 삼중 해자', 'FCF 창출력 압도적 — 배당·자사주 동시 확대', '배당 21년 연속 증액'],
          },
          riskFactors: ['AI 투자 회수 속도(가장 큰 변수)', '규제(반독점) 리스크', '달러/원 환율 — 원화 강세 전환 시 환차손', '경기 침체 시 기업 IT 지출 둔화'],
          dividend: { perShare: 0.91, currency: 'USD', frequency: '분기', schedule: '분기 $0.91 (연 $3.64) — 9·12·3·6월 지급, 매년 9월 증액 발표 관행', yieldPct: 0.94, next: '배당락 2026-08월 중순 예상', note: '12개월 보유 시 4회 수령 (연 $3.64/주)' },
          simId: 'long-msft',
        },
        {
          id: 'long-ko', ticker: 'KO', name: '코카콜라 (배당)', market: 'US', exchange: 'NYSE', currency: 'USD',
          horizon: 'long', risk: 'low',
          refPrice: 82.04, refPriceAsOf: '2026-06-30 종가(달러)',
          buy:  { window: '2026-07-08–09-10 분할 (미국 ET)', windowKst: '7–9월 초 분할 매수 (9월 중순 배당락 전 완료)', low: 78, high: 83, note: '차기 배당락(9/11–15 예상) 전 매집 완료 — 배당 4회 수령 시작.' },
          sell: { window: '2027-07월 이후 검토', windowKst: '원칙적 장기 보유 — 2027년 하반기 리밸런싱 시 검토', low: 90, high: 95, stop: 72, note: '배당 수령이 주목적 — 시세차익은 부수적. $72 이탈 시에만 정리.' },
          expectedReturn: { base: 7.4, bull: 15.8, bear: -12.2 },
          scenarios: [
            { name: '낙관', prob: 30, price: 95, ret: 15.8, desc: '디펜시브 선호 + 배당 성장 프리미엄' },
            { name: '기본', prob: 50, price: 88, ret: 7.3, desc: '완만한 우상향 + 배당 2.6%' },
            { name: '비관', prob: 20, price: 72, ret: -12.2, desc: '소비 둔화 — 손절 기준 이탈' },
          ],
          rationale: {
            summary: '64년 연속 배당 증액의 배당왕. 연 $2.12(수익률 2.56%), 분기 $0.53 — 시장 과열 경고(S&P 연말 목표 -5%)가 나오는 국면에서 방어적 배당 코어로 편입. 9월 중순 배당락 전 매집이 포인트.',
            news: ['최근 분기배당 $0.53 — 7/1 지급 완료', '차기 배당락일 9/11–15 예상 — 매수 데드라인', '시장 과열 경고 속 디펜시브 로테이션 수혜 후보'],
            technical: ['$78–80 장기 지지 밴드', '$85 전고 저항 — 돌파 시 $90대', '변동성 연 14% — 포트 안정화 역할'],
            fundamental: ['배당 64년 연속 증액 — 배당컷 위험 극히 낮음', '글로벌 브랜드 가격 결정력 — 인플레 전가 능력', '배당성향 관리 양호'],
          },
          riskFactors: ['금리 재상승 시 배당주 상대 매력 하락', '건강 트렌드발 탄산 수요 둔화', '달러 강세 시 신흥국 매출 환산 감소', '환율(원화 기준 수익률 변동)'],
          dividend: { perShare: 0.53, currency: 'USD', frequency: '분기', schedule: '분기 $0.53 (연 $2.12) — 4·7·10·12월 지급', yieldPct: 2.56, next: '배당락 2026-09-11~15 예상, 지급 10/1', note: '12개월 보유 시 4회, 주당 연 $2.12 (세전)' },
          simId: 'long-ko',
        },
        {
          id: 'long-samsung', ticker: '005930.KS', name: '삼성전자 (장기)', market: 'KR', exchange: 'KRX', currency: 'KRW',
          horizon: 'long', risk: 'mid',
          refPrice: 296000, refPriceAsOf: '2026-07-07 종가(원)',
          buy:  { window: '2026-07-09–09-30 매월 분할 (한국 KST)', windowKst: '7–9월 매월 2회, 총 6회 분할 매수', low: 270000, high: 300000, note: '실적 쇼크 조정을 장기 분할 매수 기회로 — 27만원 접근 시 비중 확대.' },
          sell: { window: '2027-04월–07월 (한국 KST)', windowKst: '2027년 2분기 중 분할 매도', low: 400000, high: 450000, stop: 240000, note: '증권가 목표 50만원의 80~90% 구간에서 단계적 실현. 240,000원 이탈 시 사이클 논리 재점검.' },
          expectedReturn: { base: 14.9, bull: 41.9, bear: -18.9 },
          scenarios: [
            { name: '낙관', prob: 30, price: 420000, ret: 41.9, desc: 'HBM 점유율 회복 + 파운드리 흑자전환' },
            { name: '기본', prob: 45, price: 370000, ret: 25.0, desc: '메모리 슈퍼사이클 지속 — 사상 최고 영역' },
            { name: '비관', prob: 25, price: 240000, ret: -18.9, desc: '사이클 피크아웃 — 손절 기준' },
          ],
          rationale: {
            summary: 'HBM4 최초 양산 + HBM4E 샘플 출하로 기술 리더십 회복 국면. 실적 쇼크로 열린 밸류에이션 갭에서 12개월 분할 매수 — 증권가 목표 50만원 대비 -40% 지점. 분기배당(연 1,444원)으로 보유 비용 상쇄.',
            news: ['증권가 목표 500,000원 — 현재가 대비 +69%', 'HBM4E 슈퍼사이클 진입 — AI 서버 투자 확대 지속', '반도체 국가 지원책(5,180억 달러 규모 계획) 수혜 논의'],
            technical: ['272,000–285,000 중기 지지 밴드', '월봉 상승 추세 유지 — 쇼크는 추세 내 조정', '340,000(전고점) 돌파 시 신고가 영역'],
            fundamental: ['메모리+파운드리+모바일 복합 포트폴리오', '주주환원 정책 — 분기배당 + 자사주 소각', 'HBM 점유율 회복이 리레이팅 핵심 변수'],
          },
          riskFactors: ['메모리 사이클 피크아웃 시점(최대 변수)', 'HBM 경쟁(SK하이닉스·마이크론) 심화', '지정학·수출 규제', '원화 환율 — 수출 채산성'],
          dividend: { perShare: 1444, currency: 'KRW', frequency: '분기', schedule: '분기 361원 × 4회 = 연 1,444원 (5·8·11월·익년 4월 지급)', yieldPct: 0.49, next: '2026-08월 지급 예정', note: '12개월 보유 시 4회 수령, 15.4% 원천징수 후 실수령' },
          simId: 'long-samsung',
        },
      ],
    },
  ],
};
